### ISSUE TITLE
Need advertising IP when using VIP or binding 0.0.0.0

### ISSUE THREAD

**Issue by linxiulei** [containerd/cri#1011]
CriService is using `StreamServerAddress` to serve function `GetExec`. There may be some cases that `GetExec` would return unusable url.

1. Configured StreamServerAddress of CriService  to "0.0.0.0", `GetExec` would return "https://0.0.0.0:$port/exec/$token", however client connected cri using real ip
2. client connected cri using VIP and the url `GetExec` returned is not connectible.

Proposal: Add a new config item of `advertise_stream_server_address`, `GetExec` would refer to it when composing Exec url. And when it's null, it fallback to use StreamServerAddress

**Comment by Random-Liu** [comment]
@linxiulei What containerd version are you using?

This should have been fixed in containerd 1.2. https://github.com/containerd/cri/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/server/streaming/server.go#L243

**Comment by linxiulei** [comment]
yeah, my containerd got a little out of date. The first case was fixed. How do you think about the second case, thx

**Comment by linxiulei** [comment]
We have two cases here, 1) apiserver (redirect mode) and we want to use vip for every node instead of host ip. 2) we setup a standalone kubelet and connect it through a proxy IP. In the second case it would be better if containerd could redirect exec url with original host, however since it's a grpc call, it didn't get original host.
