### ISSUE TITLE
Add RestartSandbox()

### ISSUE THREAD

**Issue by linxiulei** [containerd/cri#1022]
Kubelet will kill pod and run a new sandbox when process `pause` is somehow killed, this whole stop and run a new sandbox process is kinda over consuming (teardown/setup cni, delete/create container etc). What if there is a cri interface `RestartSandbox()` that just simply restart the sandbox container like a normal  container.

**Comment by mikebrow** [comment]
The only scenario I can think of where the sandbox pause process could be killed and restarted without all the teardown/setup steps is if the pod had no containers.

**Comment by linxiulei** [comment]
What if all other containers were killed and the sandbox was the last one really to dead, in which we have no reason going through whole setup process again. Except for a safer solution.

Anyhow if pause was killed, all other containers were to be killed, right? If we want a alwaysrestart pod, this wouldn’t be a rare case.

**Comment by mikebrow** [comment]
> Anyhow if pause was killed, all other containers were to be killed, right? 

Yes, I believe if the pod process has been killed by some manual or spurious event, then the pod should be stopped (the fate of the pod and all pod containers was determined by the pod container process being killed) which results in the stopping/killing of it's now orphaned containers.

However, this is a "violent" event. Pods are not supposed to be killed this way. Pods are supposed to be gracefully shut down giving the pod's containers the opportunity to go down gracefully.

> If we want a alwaysrestart pod, this wouldn’t be a rare case.

It should be a very rare case that the pod container process was killed, manually or by some spurious event. The normal process would be the pod's controller managing the lifecycle of the pod vs a user killing it out of band. What is the context of the scenario you are thinking about?

> What if all other containers were killed and the sandbox was the last one really to dead, in which we have no reason going through whole setup process again(maybe just cni, those namespaces must be recreated anyway ). Except for a safer solution.

Pod lifecycles are managed by kube controller(s) which are from the CRI runtime. To manage the restart policy of the pod, one must be or be using a controller. I believe to support your scenario we'd have to have some kind of hand off of the controller management functions to the CRI runtime.

**Comment by linxiulei** [comment]
Lots of information, thanks

> What is the context of the scenario you are thinking about?

It could be a very rare case I came into. When creating a Pod the sandbox may not start successfully (failed to pull image or some other reasons need to retry) and then the sandbox will be tear down and setup again and again. It's not a big deal in current codes, however if that cni is a big overhead would be an annoying problem : )

**Comment by mikebrow** [comment]
I see, yes that would be annoying. Did the loop eventually timeout? We might need to consider adding better error handling, possibly even load a locally cached version of pause container if there is no external connectivity since there is a possibility that the containers we run are locally loaded ones. Hmm.

**Comment by linxiulei** [comment]
I don’t think there is timeout in creating pod with kubelet, which would

**Comment by mikebrow** [comment]
True. Just thinking out loud, we could consider building our own or just add it to the list of stuff you get along with containerd/cri to seed the cache in the case where we are running disconnected.

**Comment by resouer** [comment]
Aha, @linxiulei  this is CRI implementation repo for containerd, if you hope to propose change to CRI, you need to file issue in https://github.com/kubernetes/kubernetes and ping sig-node :-)

While, as @mikebrow 's detailed https://github.com/containerd/cri/issues/1022#issuecomment-454869282, "restart" pod is actually what we trying to avoid at the very beginning when designing CRI, it goes against with how Kubernetes assume with Pod lifecycle mgmt.

**Comment by linxiulei** [comment]
> Aha, @linxiulei this is CRI implementation repo for containerd, if you hope to propose change to CRI, you need to file issue in https://github.com/kubernetes/kubernetes and ping sig-node :-)

@resouer yes, you're right. This issue may have a little out of topic, I will close it if nobody here wants to discuss it anymore : )

> While, as @mikebrow 's detailed #1022 (comment), "restart" pod is actually what we trying to avoid at the very beginning when designing CRI, it goes against with how Kubernetes assume with Pod lifecycle mgmt.

I got it, although, the "restart" do exists and current solution is not the best, we got to find a way to improve it.

**Comment by mikebrow** [comment]
we are pinning the pause image now.. issue closed

**Comment by linxiulei** [comment]
Been out of this for a long while. Glad to hear it's fixed. But could you elaborate on the pinning or point me the commit that does the work?
