### ISSUE TITLE
make test-cri returns odd error

### ISSUE THREAD

**Issue by xibz** [containerd/cri#1036]
When running `make test-cri`, I get `-runtime-handler` flag error, saying that isn't a valid flag. In addition, when modifying the `hack/test-cri.sh` file to not include the `--runtime-handler` field,  and everything succeeds.

**Comment by mikebrow** [comment]
That was added here: https://github.com/kubernetes-sigs/cri-tools/pull/405

meaning you're cri-tools in your path is out of date..

running `make install.deps` should take care of that :-)

**Comment by mikebrow** [comment]
it may succeed due to the defaults still working...

**Comment by xibz** [comment]
@mikebrow - That was exactly it. Thank you :).
