### ISSUE TITLE
AddProcessEnv has performance issue.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1044]
[AddProcessEnv](https://github.com/opencontainers/runtime-tools/blob/master/generate/generate.go#L466) uses a loop to override envs.

For a container with 26000 environment variables, this operation takes **>40s**......

We should use a map for this operation, like what docker is doing https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/container/env.go#L9.

We should audit other functions we use from runtime-tools to avoid similar performance issue.

**Comment by Random-Liu** [comment]
I think the other "for" loops in https://github.com/opencontainers/runtime-tools/blob/master/generate/generate.go are fine.

**Comment by mikebrow** [comment]
```
	env := fmt.Sprintf("%s=%s", name, value)
	for idx := range g.Config.Process.Env {
		if strings.HasPrefix(g.Config.Process.Env[idx], name+"=") {
			g.Config.Process.Env[idx] = env
			return
		}
	}

```
oh my
