### ISSUE TITLE
Kubernetes 1.10 is no longer supported

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1052]
Given that kubernetes 1.10 is end of life.. update the CRI table to bump kubernetes to 1.11+ 

See:
https://github.com/kubernetes/sig-release/issues/450

Will need to bump the test buckets as well to no longer test on 1.10

**Comment by mikebrow** [comment]
https://github.com/kubernetes/test-infra/pull/11203/files

**Comment by dmcgowan** [comment]
When we released containerd 1.1 we set its EOL for `max(April 23, 2019, Kubernetes 1.10 EOL)`. We should start thinking about whether we should update that to a newer version of K8s, define an "extended" support time, or EOL it in April.

**Comment by Random-Liu** [comment]
Sent https://github.com/kubernetes/test-infra/pull/11297 to update the test to test against K8s 1.11

**Comment by Random-Liu** [comment]
We've updated the test infra and the support metrics. I think we can close this one.
