### ISSUE TITLE
Add configurable timeout for idle streaming connections

### ISSUE THREAD

**Issue by rtheis** [containerd/cri#1057]
The [Center for Internet Security](https://www.cisecurity.org/) has a Kubernetes security benchmark which recommends setting `--streaming-connection-idle-timeout` on `kubelet` to close idle streaming connections to containers.  Looking closer at the Kubernetes code shows this only works for Docker (see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L620).  I confirmed that `--streaming-connection-idle-timeout` doesn't control the containerd timeout for streaming idle connections.   Rather, it appears that containerd has a hard-coded 4 hour timeout.  The timeout is necessary but may not be sufficient for compliance reasons (e.g. HIPPA) which may require faster timeouts.  This issue is requesting a configurable containerd CRI timeout for idle streaming connections.  While it would be nice to drive this configuration from Kubernetes, it is not required.

**Comment by Random-Liu** [comment]
> While it would be nice to drive this configuration from Kubernetes, it is not required.

I think we'll remove the kubernetes configuration when dockershim is deprecated. Let's add a containerd config option.

**Comment by mikebrow** [comment]
It may take a considerable amount of time before dockershim is deprecated.

It's not required, but In the past with respect to issues such as this we have done our best to replicate dockershim's behavior.  

I agree this is a node config issue, and as such our config can be different than the default.

I'm a bit nervous about not supporting the --streaming-connection-idle-timeout when it's been requested. Seems like a bug. At a minimum we should probably ask kublet to throw an error when it's been specified and it "will not" be supported by (or passed to) non Docker shim CRI implementations. Further, this might be an issue if a customer of containerd wants one timeout for the k8s namespace and another for containerd/docker namespaces.

In the back of my mind I was thinking this should be in kublet but a part of the pod / container spec. Maybe discuss this at the next sig.node call?
