### ISSUE TITLE
Deprecate the RuntimeHandler field in SandboxInfo

### ISSUE THREAD

**Issue by haiyanmeng** [containerd/cri#1064]
A new field called [runtime_handler](https://github.com/kubernetes/kubernetes/blob/7dbe426b2426458f02339e28d1cc102efdb6eda1/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L444) has been added into the CRI PodSandboxStatus in https://github.com/kubernetes/kubernetes/pull/73833.

https://github.com/containerd/cri/pull/1063 adds RuntimeHandler into PodSandbox and PodSandboxStatus in cri-containerd.

The [RuntimeHandler](https://github.com/containerd/cri/blob/ec3aa445911a6eb1ae7ebe9277d8da6bebb8627a/pkg/server/sandbox_status.go#L124) field in SandboxInfo will be deprecated after containerd 1.3, should not be used in the new code.

**Comment by Random-Liu** [comment]
We should put the deprecation announcement in the 1.3 release note, and then repurpose the issue to track the actual deprecation after that.

**Comment by Random-Liu** [comment]
This is going to be included in https://github.com/containerd/containerd/pull/3492.
