### ISSUE TITLE
Use per-pod shim.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1075]
We should start testing per-pod shim introduced by https://github.com/containerd/containerd/pull/3004.

And for containerd 1.3, we should switch to using that for Kubernetes.

We observed memory regression in golang 1.12 https://github.com/kubernetes/kubernetes/issues/74917.
Since we have a per-container containerd-shim now, the overall memory usage is pretty sensitive to golang runtime memory overhead.

Moving to per-pod shim should make this much better.

/cc @crosbymichael FYI

**Comment by crosbymichael** [comment]
SGTM

**Comment by mikebrow** [comment]
makes a lot of sense

**Comment by jterry75** [comment]
@Random-Liu - This is exactly what we did for the Windows runtimes. I think its perfectly reasonable approach. I'm not sure the behavior on Linux but for us it also provides a nice behavior where if we need to kill a "pod shim" the entire pod and all resources are destroyed together. 

I think it should be as easy as updating the config for the default runtime. Our code detects this fully from the sandbox id annotation in the bundle at shim start so I don't think any code changes are required.

**Comment by Random-Liu** [comment]
https://github.com/containerd/cri/pull/1116 enabled per-pod shim in the Kubernetes e2e test.

If the test result looks good, we may want to consider whether we should switch default in https://github.com/containerd/cri/blob/master/pkg/config/config.go#L200.

@crosbymichael Do we have all shim binaries packaged in the containerd package in different OS distributions?

**Comment by mikebrow** [comment]
We could switch it in master only.. to get feedback now, and document how to go back to the prior default if it causes someone problems.

**Comment by Random-Liu** [comment]
Here is the memory usage change:
![image](https://user-images.githubusercontent.com/5821883/55648699-d95cec00-5795-11e9-8bb9-7fc7a625bdf4.png)

RSS: ~360mb -> ~280mb.

Not as significant as I thought, but still good to have. And the test only has one container per-pod, for multiple containers a pod the memory usage save should be more significant.

However, we need to fix https://github.com/containerd/containerd/issues/3177 before making this default.

**Comment by Random-Liu** [comment]
This has been running in containerd Kubernetes e2e test for a month.

I think we are good. :)

> If the test result looks good, we may want to consider switching default in https://github.com/containerd/cri/blob/master/pkg/config/config.go#L200.

I 'm leaning to not to switch the default config yet, because we are not sure whether all distributions will ship the runc-v2 shim binary. Let's still leave the choice to cluster admin.
