### ISSUE TITLE
[config] Move DefaultRuntime to Runtimes

### ISSUE THREAD

**Issue by tallclair** [containerd/cri#1076]
We are planning some changes to RuntimeClass for beta in v1.14 that will make it harder to select the default runtime. The goal is to make the runtime handler selection more explicit, so best practices would be to have a "runc" runtime defined in the [`Runtimes` map](https://github.com/containerd/cri/blob/95f564f95bbc0091ff229a8b707dd9f310aae089/pkg/config/config.go#L58). The problem is, that would make users duplicate the configuration for the `DefaultRuntime`.

I propose that we introduce a new field, `DefaultRuntimeName string` (or an alternative name) that simply maps the default to a key in the runtimes map. We would also want to deprecate the `DefaultRuntime` field, and validate that:
1. `DefaultRuntime` & `DefaultRuntimeName` are mutually exclusive
2. `DefaultRuntimeName` actually maps to a value in `Runtimes`

This is my preferred solution, but alternatively we could give the default runtime the same treatment we used for the UntrustedWorkloadRuntime. That is, allow the runtime_handler `default` to select choose the default runtime, and optionally define a `default` runtime in the runtimes map rather than specifying the `DefaultRuntime`. The problem with this approach is it goes against the goal of making the runtime_handler explicit, as `default` doesn't really describe which runtime handler is being used.

**Comment by tallclair** [comment]
Any concerns with the proposed approach? If this SG, I'm happy to open a patch. When is the cutoff for 1.3?

/cc @Random-Liu @mikebrow

**Comment by mikebrow** [comment]
I think we can do this without a new field.

Should be ok to add runc as an explicit runtimes entry, and modify defaultruntime.runtimetype value to point to the runtimes runc by default vs "io.containerd.runtime.v1.linux"

The untrusted model has been deprecated already as have the extra defaultruntime fields.

**Comment by tallclair** [comment]
@mikebrow - I'm not sure if I understand correctly. Are you suggesting that we repurpose the runtime_type field on the default runtime to be an alias to a runtimes entry? How would containerd know whether to treat it as an actual runtime_type or an alias? Would we allow aliasing runtimes in the list too? (e.g. "native" -> "runc")

**Comment by tallclair** [comment]
BTW, I went to file a similar bug on CRI-O, but found that they already treat the default this way (runtime name).

**Comment by mikebrow** [comment]
> @mikebrow - I'm not sure if I understand correctly. Are you suggesting that we repurpose the runtime_type field on the default runtime to be an alias to a runtimes entry? 

Yes.

> How would containerd know whether to treat it as an actual runtime_type or an alias? 

I don't think it matters.

> Would we allow aliasing runtimes in the list too? (e.g. "native" -> "runc")

That should work. You should be able to have as many different runc configs as you like.

> BTW, I went to file a similar bug on CRI-O, but found that they already treat the default this way (runtime name).

I'm not sure what the bug is.

**Comment by tallclair** [comment]
> I'm not sure what the bug is.

s/bug/issue/ - I really meant feature request.

**Comment by Random-Liu** [comment]
@mikebrow We can't use `runtime_type`. Because different runtime handlers may have the same runtime type, for example:
1) The legacy runtime type `io.containerd.runtime.v1.linux` is used for all v1 shim runtimes;
2) Even for v2 shim, we may want to have 2 runtime handlers for the same runtime type but with different configurations, e.g.: `kata-firecracker` for `io.containerd.kata.v2` with firecracker VMM; `kata-qemu` for `io.containerd.kata.v2` with qemu VMM.

I think adding a new field makes sense.

**Comment by mikebrow** [comment]
Not sure if I was clear.. What I meant is point the default runtime type to the key specified in runtimes.

Instead of:
```
[plugins.cri.containerd.default_runtime]
runtime_type = "io.containerd.runtime.v1.linux"
```
go with:
```
[plugins.cri.containerd.default_runtime]
runtime_type = "runc"
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
         runtime_type = "io.containerd.runtime.v1.linux" #or my runcconfig yada yada
         [plugins.cri.containerd.runtimes.runc.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "runc"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false```
```
I suppose name (or runtimeKey?) would have the same effect. I think name is what threw me off.

**Comment by mikebrow** [comment]
But yeah something like this works:
```
[plugins.cri.containerd.default_runtime]
runtime_key = "runc"
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
         runtime_type = "io.containerd.runtime.v1.linux" #or my runcconfig yada yada
         [plugins.cri.containerd.runtimes.runc.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "runc"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
```

**Comment by tallclair** [comment]
I guess the part that confused me was that runtime_type could now mean 2 different things, so wouldn't containerd need some way of knowing which meaning was intended?

**Comment by mikebrow** [comment]
> I guess the part that confused me was that runtime_type could now mean 2 different things, so wouldn't containerd need some way of knowing which meaning was intended?

ah I see.. yeah the type was just a string mapping to a known set of defaults which are now specified in the new runtimes option as a runtime mapped by a key... So to me the type can be "repurposed" as a "key" pointing to a runtime in the runtimes list. Or we can add a new field.. works for me either way.
