### ISSUE TITLE
Consider load cni conf in a goroutine to prevent stuckup in Status

### ISSUE THREAD

**Issue by linxiulei** [containerd/cri#1078]
When cni plugin is setting up a interface for a long time (>30s), a RLock is hold, which would prevent Load() to continue. Meanwhile cri Status() tried to load cni config and check it with Status(), see

https://github.com/containerd/cri/blob/95f564f95bbc0091ff229a8b707dd9f310aae089/pkg/server/status.go#L47

it will case hang until the setup is finished. So I guess we'd better load the config in an async goroutine.

**Comment by mikebrow** [comment]
hmm...

**Comment by Random-Liu** [comment]
The request sounds reasonable to me. Let's find a way to avoid the hang up.

**Comment by Random-Liu** [comment]
https://github.com/containerd/go-cni/pull/37 avoids the hung up.
