### ISSUE TITLE
load images from tarball without repo tags

### ISSUE THREAD

**Issue by zhouhaibing089** [containerd/cri#1079]
Today, when we save an image from docker image ID into tarball, and then try to load it with `ctr cri load <image>.tar`, nothing is gonna to happen.

```console
$ docker images
...
hub.tess.io/kubernetes/pause                       0.8.0                        bf595365a558        3 years ago         242kB
$ docker save bf595365a558 -o bf595365a558.tar
$ tar xf bf595365a558.tar
tar: manifest.json: implausibly old time stamp 1969-12-31 17:00:00
$ cat manifest.json
[{"Config":"bf595365a5588ec1bae3e9dc9efde13672f7b7561b6cc4514a82f07be9d01ca6.json","RepoTags":null,"Layers":["5c9b3bc6c97a13bd007352809ff8477d875508cd4c7de2a2614b4a7c424bfb2e/layer.tar","58b1000336114fedb143389349b4a233ec3630c812a30ee714405b6e7e37d8c3/layer.tar","1084d26384c630c366b780ccedbe1184c2e729d115e6c1b88895935345bba43c/layer.tar"]}]
$ ctr cri load bf595365a558.tar
$ ctictl images list
// nothing
```

**Comment by zhouhaibing089** [comment]
cc @Random-Liu

**Comment by Random-Liu** [comment]
The cri plugin uses image id as the unique identifier for an image, so we do support images without any repotags or repodigests (the same with Docker).

We just need to add the image id as well during image load.

**Comment by zhouhaibing089** [comment]
The counter part of `ctr` works though:

```console
$ ctr --address=/var/containerd/containerd.sock --namespace=k8s.io images import --digests <image id>.tar
```

Though it is required to specify `--digests`.

**Comment by Random-Liu** [comment]
That's cool. One option we can look into is to start deprecating `ctr cri load` and just let people use `ctr images import`.

Ref https://github.com/containerd/cri/issues/909.

**Comment by Random-Liu** [comment]
@dmcgowan Is it possible to add a `--id` flag in `ctr images import` command, so that we can:
1) Import images with not tags (this issue)
2) Have id ready, which CRI plugin needs anyway.

**Comment by Random-Liu** [comment]
We've deprecated `ctr cri load` and supported `ctr images import`.

I think this issue can be marked resolved.
