### ISSUE TITLE
Do not mask for privileged containers

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1089]
Kublet expects CRI implementations to not apply the masks it passed when the container is privileged... See: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L140-L143

and over here:

https://github.com/kubernetes/kubernetes/issues/75238

I'll push a PR

**Comment by Random-Liu** [comment]
We've been doing this https://github.com/containerd/cri/blob/c483f8c2775efc373cb80e8d1087f07a33c07eb7/pkg/server/container_create.go#L772-L773

**Comment by mikebrow** [comment]
missed it in the call 10 lines down. :-) When they reported the failure... I figured we must be broken here. Thx I'll just change the PR to an add a test case PR, and go chase down the issue report to see what else could've happened.  Cheers!
