### ISSUE TITLE
ctr cri load failed!

### ISSUE THREAD

**Issue by wubo0067** [containerd/cri#1100]
[root@katak8s-1 /]# crictl -v
crictl version v1.14.0

[root@katak8s-1 /]# ctr -v
ctr github.com/containerd/containerd v1.2.5

[root@katak8s-1 /]# cat /etc/crictl.yaml 
runtime-endpoint: **unix:///var/run/crio/crio.sock**
image-endpoint: **unix:///var/run/crio/crio.sock**
debug: true
timeout: 10

[root@katak8s-1 /]# crictl images
IMAGE                                        TAG                 IMAGE ID            SIZE
docker.io/coredns/coredns                    1.2.6               f59dcacceff45       40.3MB
docker.io/ibmcom/etcd                        3.2.24              33bdcac177c2a       220MB
docker.io/ibmcom/pause                       3.1                 da86e6ba6ca19       747kB
docker.io/jmgao1983/flannel                  v0.11.0-amd64       ff281650a721f       55.4MB
docker.io/library/busybox                    latest              d8233ab899d41       1.42MB
docker.io/openstackmagnum/kubernetes-proxy   v1.13.4             ea72813426f4d       82.1MB

[root@katak8s-1 /]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.13.4             8cd8b6b54266        3 weeks ago         80.3MB
k8s.gcr.io/kube-scheduler            v1.13.4             b178b0b20ff2        3 weeks ago         79.6MB
k8s.gcr.io/kube-controller-manager   v1.13.4             4b96a2880c0b        3 weeks ago         146MB
k8s.gcr.io/kube-apiserver            v1.13.4             8dcfc55e6a49        3 weeks ago         259MB
quay.io/coreos/flannel               v0.11.0-amd64       ff281650a721        8 weeks ago         52.6MB
k8s.gcr.io/coredns                   1.2.6               f59dcacceff4        4 months ago        40MB
k8s.gcr.io/etcd                      3.2.24              33bdcac177c2        5 months ago        220MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        15 months ago       742kB

Now I want import kube-proxy from Docker Image
[root@katak8s-1 /]# docker save k8s.gcr.io/kube-proxy:v1.13.4 -o kube-proxy.tar
[root@katak8s-1 /]# ctr cri load kube-proxy.tar 
**ctr: failed to load image: rpc error: code = Unimplemented desc = unknown service api.v1.CRIPluginService**

**Comment by Random-Liu** [comment]
Are you using cri-o?

**Comment by Random-Liu** [comment]
If you are using docker 18.09+, you need to enable the cri plugin if you want to use CRI in containerd.

See this issue https://github.com/containerd/containerd/issues/3101.

**Comment by wubo0067** [comment]
@Random-Liu thanks
