### ISSUE TITLE
TLS auth with image registries 

### ISSUE THREAD

**Issue by ungureanuvladvictor** [containerd/cri#1143]
When using Docker we had https://docs.docker.com/engine/security/certificates/ but now when we moved to containerd/cri we deployed an nginx proxy to do the TLS off-loading.

Any plans to support TLS auth with image registries? I took a stab at it via https://github.com/ungureanuvladvictor/cri/commit/c15fc1237233664e344e1eb3512c05cda18c570d just to see how it would look like.

**Comment by Random-Liu** [comment]
That is very welcome! Feel free to submit your change. We'll review it. :)

**Comment by ungureanuvladvictor** [comment]
@Random-Liu thx for the ping back. I will open the PR as is and we should continue the discussion there. This is my 1st time diving into `cri` code so would be fun!

**Comment by mikebrow** [comment]
ok.. Interesting.  Has there been discussion for how will this mesh with the current kubernetes secrets pattern? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ 

Cheers, Mike

**Comment by ungureanuvladvictor** [comment]
I am aware of this but did not put a lot of thought into it. We currently run a couple of static pods which also includes the apiserver so bootstrapping won't really work in my case but happy to chat.

**Comment by Random-Liu** [comment]
> ok.. Interesting. Has there been discussion for how will this mesh with the current kubernetes secrets pattern? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

I think this proposal is more about TLS between container runtime and container image registry, not the authentication to the image registry.

**Comment by mikebrow** [comment]
> > ok.. Interesting. Has there been discussion for how will this mesh with the current kubernetes secrets pattern? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
> 
> I think this proposal is about TLS between container runtime and container image registry, not the authentication to the registry.

ok.. sort of thought it was going to be for bootstraping

**Comment by ungureanuvladvictor** [comment]
In my case I have a registry that requires TLS mutual authentication which needs the client to present a certificate when it establishes the connection.
