### ISSUE TITLE
Add support for traffic shaping

### ISSUE THREAD

**Issue by johscheuer** [containerd/cri#1150]
Kubernetes added support for traffic shaping (https://github.com/kubernetes/kubernetes/pull/63194/files) the changes in the linked PR are only for Docker in order to support traffic shaping with containerd we need to implement the missing "glue". I also added some docs how I tested/installed the bandwidth plugin. With Docker everything worked as expected but with containerd there were no effect (since the cri currently doesn't support it). 

I would like to work on this. I also already created a PR for the go-cni library https://github.com/projectcalico/calico/issues/797#issuecomment-493210584

**Comment by Random-Liu** [comment]
Let's support this in containerd 1.3. Thanks for reporting!
