### ISSUE TITLE
Make cni plugin config file num configurable

### ISSUE THREAD

**Issue by kuramal** [containerd/cri#1154]
Make cni plugin config file num configurable， let containerd can make  mutil network card

**Comment by Random-Liu** [comment]
CRI only reports one pod IP, how the other NICs of the pod will be used?

I'm fine with this change, just want to understand the background more. :)

**Comment by Random-Liu** [comment]
@kuramal SG. Get the go-cni change in first, and then update the vendor on the CRI side.

**Comment by kuramal** [comment]
@Random-Liu  hi, the pr of go-cni,  have already merged. Should I update the go-cni code of vendor, or just update the commit id in vendor.conf?

**Comment by Random-Liu** [comment]
@kuramal Yeah! :D

**Comment by Random-Liu** [comment]
#1155 is merged, this can be closed. @kuramal Thanks for adding this support! :)
