### ISSUE TITLE
Switch to version 2 containerd config

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1168]
For enforcing unique plugin identifier https://github.com/containerd/containerd/issues/3210, we introduced the version 2 containerd config https://github.com/containerd/containerd/pull/3322

In the CRI plugin, we need to:
1) Test the version 2 config;
2) Update the document for version 2 config.

**Comment by mikebrow** [comment]
thx Lantau

**Comment by Random-Liu** [comment]
The document update is done in https://github.com/containerd/cri/pull/1188

Thanks @alculquicondor
