### ISSUE TITLE
containerd daemon does not handle image pulling, breaking http_proxy

### ISSUE THREAD

**Issue by joedborg** [containerd/cri#1169]
Containerd does not handle image pulling.  This breaks things such as pulling images via http_proxy.  Instead, containerd relies on the client (e.g. `ctr`) to pull the image (thus also handling proxy settings).

Can be reproduced by setting up a local http proxy, adding those details to the systemd service file for `containerd`, pulling an image via a client (`crictl`, `ctr` or kubernetes).  You'll see, from the proxy's logs that no attempt is made via the proxy.  However, setting these env vars whilst in the clients' environment will access via the proxy.  E.g.

```bash
HTTP_PROXY=localhost:8000 HTTPS_PROXY=localhost:8000 ctr image pull docker.io/library/hello-world:latest
```

**Comment by mikebrow** [comment]
@Random-Liu @abhi we need to add support in our CRI image pull resolver... to support HTTP?_PROXY environment vars like ctr does. See CTR's GetResolver here: https://github.com/containerd/containerd/blob/master/cmd/ctr/commands/resolver.go#L83

As seen ^ we let http handle such proxy issues in the ctr client.

**Comment by Random-Liu** [comment]
We should do it.

**Comment by Random-Liu** [comment]
Actually I found that we are using `http.DefaultClient`, and it is using the `http.DefaultTransport`:
```
var DefaultTransport RoundTripper = &Transport{
        Proxy: ProxyFromEnvironment,
        DialContext: (&net.Dialer{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
                DualStack: true,
        }).DialContext,
        MaxIdleConns:          100,
        IdleConnTimeout:       90 * time.Second,
        TLSHandshakeTimeout:   10 * time.Second,
        ExpectContinueTimeout: 1 * time.Second,
}
```
https://golang.org/pkg/net/http/#RoundTripper

This should work. @joedborg What version of containerd are you using?

**Comment by Random-Liu** [comment]
I tried it, it should work:
```systemd
[Unit]
Description=containerd container runtime
Documentation=https://containerd.io
After=network.target

[Service]
Environment=HTTP_PROXY=localhost:8000
Environment=HTTPS_PROXY=localhost:8000
ExecStartPre=/sbin/modprobe overlay
ExecStart=/usr/local/bin/containerd
Restart=always
RestartSec=5
Delegate=yes
KillMode=process
OOMScoreAdjust=-999
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

```shell
$ crictl pull busybox
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "docker.io/library/busybox:latest": no available registry endpoint: failed to do request: Head https://registry-1.docker.io/v2/library/busybox/manifests/latest: proxyconnect tcp: dial tcp [::1]:8000: connect: connection refused 
```

**Comment by joedborg** [comment]
I’m using 1.2.6.  Would we expect crictl to behave differently than ctr?

**Comment by mikebrow** [comment]
@joedborg yes the there is different code in ctr for pulling images than is in the crictl->containerd/cri path.. maybe we can "normalize" that a bit.

**Comment by Random-Liu** [comment]
> I’m using 1.2.6.

Let me try 1.2.6.

> Would we expect crictl to behave differently than ctr?

Yes.
* For `ctr` the image pull happens in the ctr process, so you want to set env for the `ctr` process.
* For `crictl` the image pull happens in the CRI plugin, which is built as part of containerd, so you need to set env of the `containerd` process.


@joedborg Yeah,
