### ISSUE TITLE
wired behavior about makefile

### ISSUE THREAD

**Issue by ZYecho** [containerd/cri#1172]
if you run `make` under /cri and you got containerd and ctr binary in `_output`, but if you run `make` again next,  and try to remove the binary containerd under `_output`, you will get `rm: cannot remove 'containerd': Text file busy.
I use `lsof ` to check, and find a process using the binary, if you kill the process, and you will remove it.

Based on that, I think it's a little wired, and need to report here.
I hope that it's ok to run 'make' command twice.

**Comment by mikebrow** [comment]
odd... text file? busy?
it should be a program.. and I see no reason for it to be in use.

behavior not seen here:
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ sudo make
[sudo] password for mike: 
go build -o _output/containerd \
	-tags 'seccomp apparmor' \
	-ldflags '-X github.com/containerd/cri/vendor/github.com/containerd/containerd/version.Version=3ba04c0-TEST' \
	-gcflags '' \
	github.com/containerd/cri/cmd/containerd
go build -o _output/ctr \
	-tags 'seccomp apparmor' \
	-ldflags '-X github.com/containerd/cri/vendor/github.com/containerd/containerd/version.Version=3ba04c0-TEST' \
	-gcflags '' \
	github.com/containerd/cri/cmd/ctr
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ ls _output
containerd  ctr
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ sudo rm _output/containerd
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ sudo make
go build -o _output/containerd \
	-tags 'seccomp apparmor' \
	-ldflags '-X github.com/containerd/cri/vendor/github.com/containerd/containerd/version.Version=3ba04c0-TEST' \
	-gcflags '' \
	github.com/containerd/cri/cmd/containerd
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ 
```
my go version:
go version go1.11.2 linux/amd64

**Comment by mikebrow** [comment]
suggest doing a sudo make clean in case you golang cache is messed up somehow.. then try again?

**Comment by ZYecho** [comment]
I'm not sure it's related about docker service I used, because I found `make install ` will install the containerd binary into /usr/local/bin which may pollute the environment.

**Comment by ZYecho** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by ZYecho** [comment]
go version go1.10.4 linux/amd64

**Comment by mikebrow** [comment]
We had to move up to go 1.11.x a while back, I don't remember all of the issues, but you may be seeing go build dependency issues with our code base and vendor tree. 

"pollute"... the latest docker is compatible with the latest containerd.. it should run just fine with your master built version of containerd.

**Comment by Random-Liu** [comment]
@ZYecho We just call `go build` to build binaries in `make`. And I can't reproduce it.

This seems to be something wrong in your development environment.

**Comment by ZYecho** [comment]
close now. thanks every one
