### ISSUE TITLE
Support a TCP endpoint

### ISSUE THREAD

**Issue by alculquicondor** [containerd/cri#1181]
For an scenario where:

- processes running in the machine and remote clients are trusted
- an extra TCP/socket hop is undesired.

CRI could be served in a new TCP endpoint, additionally to being served in the main containerd socket. Exposing the whole containerd server in TCP might still be a security risk containerd/containerd#1324

TLS support could be provided as well.

**Comment by mikebrow** [comment]
We can discuss this.  But IMO it really needs auth and/or tls with signed certs (not self signed) before the PR should be approved. Thus some config will be necessary to provide the certs, and/or some key repository integrated for the auth. Recognize that the typical config for container runtime integrations runs as root. Granted we'll be supporting non-root configs soon, but ... cart before the horse.

**Comment by mikebrow** [comment]
See https://github.com/containerd/containerd/commit/b911ae3428717763377d038958597383c7ed0491

^ that commit does include tls with certs so... addressed my above issue.

**Comment by alculquicondor** [comment]
I missed that feature too. I submitted a new PR :)

**Comment by Random-Liu** [comment]
I think we should close this one.

Feel free to reopen if you need anything else.
