### ISSUE TITLE
Flannel subnet.env in non default location

### ISSUE THREAD

**Issue by ktsakalozos** [containerd/cri#1197]
**Description**
Flannel creates a `subnet.env` file (by default under `/run/flannel/`) with contents similar to:
```
FLANNEL_NETWORK=10.1.2.0/24
FLANNEL_SUBNET=10.1.2.193/26
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false
``` 
There is an argument (`--subnet-file`) to instruct flannel to place this file in a non default path. But when doing so creating containers is failing with
```
Warning  FailedCreatePodSandBox  5s    kubelet, workspace  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "485cd67f4aeee61eaa09dc0676e72b6e8262ae91aeb40ddf6c830d04b682f1ef": open /run/flannel/subnet.env: no such file or directory
```   

I do not see any obvious way to inform containerd of the new path.

**Output of `containerd --version`:**

```
containerd github.com/containerd/containerd v1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

**Comment by estesp** [comment]
Hi @ktsakalozos; I'm transferring your issue to the cri repo as containerd itself does nothing with CNI configurations/plugins. If there is a solution, it will be here in the CRI plugin code. Hopefully someone can figure out why that path isn't being found and can find a resolution.

**Comment by ktsakalozos** [comment]
I missed the `subnetFile` in https://github.com/containernetworking/plugins/tree/master/plugins/meta/flannel#network-configuration-reference

Thanks @Cynerva
