### ISSUE TITLE
[bug] auth section in config.toml not taken into account

### ISSUE THREAD

**Issue by drewboswell** [containerd/cri#1214]
TLDR;
auto login via /etc/containerd/config.toml seems to be ignored.

# version info
containerd version: 1.2.6-3
lsb_release: Ubuntu 18.04.2 LTS
uname -a : Linux **** 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# scenario
edit /etc/containerd/config.toml
add auth section to private registry
attempt to pull from private registry (ctr image pull)
receive 401 unauthorized
check access logs on registry, no auth credentials sent.

# documentation that I followed
https://github.com/containerd/cri/blob/master/docs/registry.md

**Comment by Random-Liu** [comment]
@drewboswell The auth section is only used by the CRI plugin, `ctr image pull` won't work.

If you use Kubernetes or `crictl pull`, it should work I think.

**Comment by Random-Liu** [comment]
I'll close this for now. Feel free to reopen if you have further questions. @drewboswell
