### ISSUE TITLE
Remove extra resolve for detecting schema1 image

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1229]
Today, the CRI plugin does an extra resolve to detect schema1 image https://github.com/containerd/cri/blob/master/pkg/server/image_pull.go#L104.

I believe there is a way to get the information from containerd after the image is pulled, e.g. from a label. We should avoid the unnecessary roundtrip.

**Comment by dmcgowan** [comment]
You could also do this with a handler. The handler can just look for the schema1 handler, the base handlers always get called before the converter.

**Comment by Random-Liu** [comment]
@dmcgowan Thanks for the suggestion! Filed #1232
