### ISSUE TITLE
need to move up to cni v0.7.1 

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1236]
See https://github.com/containerd/go-cni/pull/47/

When that PR gets merged we will need to vndr it and add context to our calls to netPlugin.Setup and .Remove.

**Comment by Random-Liu** [comment]
SG. They support context now. Good!

**Comment by Random-Liu** [comment]
The context support is useful for stability when operation timeout or cancelled.

We should update CNI and support it. Mark 1.3.

https://github.com/containernetworking/cni/blob/ec5ec68fa4979e8f98c13845dbc2352380ad179b/pkg/invoke/raw_exec.go#L34
