### ISSUE TITLE
Runtime default AppArmor profile gets applied to privileged containers

### ISSUE THREAD

**Issue by praseodym** [containerd/cri#1239]
For privileged Kubernetes containers with the `runtime/default` AppArmor explicitly applied, there is a difference in behaviour between Docker and containerd.

On the one hand, dockershim [translates the `runtime/default` profile into nil](https://github.com/kubernetes/kubernetes/blob/40b31794ab6cbf92835898299f768f64d5f30619/pkg/kubelet/dockershim/helpers.go#L361-L364) (i.e. no explicit profile set). In Docker (Moby), the AppArmor profile then [only gets applied when the container is not privileged](https://github.com/moby/moby/blob/4f0d95fa6ee7f865597c03b9e63702cdcb0f7067/daemon/container_linux.go#L21-L24).

On the other hand, [kuberuntime seems to pass whatever is in the AppArmor annotation](https://github.com/kubernetes/kubernetes/blob/33081c1f07be128a89441a39c467b7ea2221b23d/pkg/kubelet/kuberuntime/security_context.go#L42-L43) and the containerd/cri `generateApparmorSpecOpts` function [will not exclude privileged containers in this case](https://github.com/containerd/cri/blob/aaf15b67771cd43bd6c5df3373d7f8e8f1fab22e/pkg/server/container_create.go#L580-L582) ([it will when no explicit profile is set](https://github.com/containerd/cri/blob/aaf15b67771cd43bd6c5df3373d7f8e8f1fab22e/pkg/server/container_create.go#L585-L591)).

I think the first behaviour makes the most sense for compatibility with Docker and dockershim, but it does mean that privileged containers will never get the runtime's default AppArmor profile applied (a workaround would be for the cluster operator to clone the default profile under a new name, and apply that instead).

Also, it could be argued that this is better fixed in the Kubelet's kuberuntime, similar to how dockershim works.

**Comment by Random-Liu** [comment]
Fixed in https://github.com/containerd/cri/pull/1240
