### ISSUE TITLE
Separate platform specific config options

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1245]
We should add `linux` and `windows` section, and put platform specific config into those sections.

Example options that don't make sense to Windows:
* `disable_cgroup`
* `disable_apparmor`
* `restrict_oom_score_adj`
* ...

**Comment by Random-Liu** [comment]
Instead of having the entire default config in config_unix.go and config_windows.go, let's clean this up and only have different parts in them.

**Comment by jterry75** [comment]
Sounds good. I just removed them from the containerd.toml so the toml file looks clean anyways. But this is better e2e
