### ISSUE TITLE
container object kind annotations

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1262]
We added pod annotations... but somehow we missed adding container annotations, which should be pod annotations + container annotations. Currently the container spec only gets the pod annotations that match the pod_annotations filter.

See #1260 and #1261 wip 

https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

I guess the question is... is a container a kubernetes object in the sense that it may have metadata (annotations and labels) we do add pod annotations to the container. It's sort of confusing from the container perspective, that the answer is no, since containers do have annotations.  It seems like a disconnect between k8s and containers.

**Comment by Random-Liu** [comment]
@mikebrow Container is not a kubernetes object.

**Comment by mikebrow** [comment]
Right... in my view that is a disconnect. I get that a pod is a kubernetes object and the containers specified within. Coming from a container centric perspective it feels odd, that for a container to have an adhoc annotation metadata it must be specified at the pod level.
