### ISSUE TITLE
Unable to build containerd with CRI-Plugin changes for test

### ISSUE THREAD

**Issue by bg-chun** [containerd/cri#1270]
### What I want to do.
I am trying to enhance `CRI Message` and `CRI-Plugin` to support hugepages.
(At this point, CRI and the plugin does not support hugepages, see [issue](https://github.com/kubernetes/kubernetes/issues/80716), [KEP](https://github.com/kubernetes/enhancements/pull/1199))

So I made some changes for CRI Message and CRI-Plugin to support hugepages.
In CRI-Plugin, I put extra log and logic to handle hugepages on `func WithResources`
https://github.com/containerd/cri/blob/6961bfa1d4dee2644a7a6f7ca87517317dd15e2a/pkg/containerd/opts/spec_unix.go#L452

### What is an issue.
But the built binary is wired.
When I run unittests by 'make test', I can see the log which i add and the result is also the same as I expected.
But the matter is building containerd binary, when I build the containerd and the CRI-Plugin by `make` or `make containerd`, it seems that the built binary doesn't include the changes of CRI-Plugin.
I can't see any logs which I add and the behaviors by the logic which I add.

### How to reproduce this issue.
To clarify, I comment the whole line of the function "WithResources" to check whether the built binary includes the changes of this package or not.
But the built binary works well so that i believe there is an issue on building the binary with the changes of CRI-plugin.

### How I test it
Below is how I build the binary and how I test it.
Please let me know if I make a mistake.

1. go get github.com/containerd/cri
2. Make the changes under pkg path.
    In my case, I comment whole line of function like below.
```
func (c *criService) UpdateContainerResources(ctx context.Context, r *runtime.UpdateContainerResourcesRequest) (retRes *runtime.UpdateContainerResourcesResponse, retErr error) {
	//container, err := c.containerStore.Get(r.GetContainerId())
	//if err != nil {
	//	return nil, errors.Wrap(err, "failed to find container")
	//}
	// Update resources in status update transaction, so that:
	// 1) There won't be race condition with container start.
	// 2) There won't be concurrent resource update to the same container.
	//if err := container.Status.Update(func(status containerstore.Status) (containerstore.Status, error) {
	//	return status, c.updateContainerResources(ctx, container, r.GetLinux(), status)
	//}); err != nil {
	//	return nil, errors.Wrap(err, "failed to update resources")
	//}
	//return &runtime.UpdateContainerResourcesResponse{}, nil
}

```
3. Build depencencies by `make install.deps`
4. Build containerd with the CRI-Plugin changes by `make` or `make containerd`
5. stop containerd by `sudo systemctl stop containerd`
6. Copy `_output/containerd` to `/usr/bin`
7. Restart node by `sudo systemctl restart kubelet containerd docker`
8. deploy pod to trigger "UpdateContainerResources" CRI Message
(CPU Manager of kublet utilizes `UpdateContainerResources` to set exlusive CPU)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpuset
spec:
  containers:
  - image: nginx
    name: nginx-cpuset
    resources:
      requests:
        cpu: "1"  //this means this container requests exclusive CPU.
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "256Mi"
```

**Comment by Random-Liu** [comment]
I guess you have a local containerd binary takes precedence.

Can you run `which containerd`?

**Comment by bg-chun** [comment]
@Random-Liu 
After building by `make install.deps` and `make` the binary was located on `/usr/local/bin/containerd`
But I removed it then copied `_output/containerd` to `/usr/bin` to test.
Because systemd config of containerd point to `/usr/bin/containerd`.
```
which containerd
/usr/bin/containerd
```

**Comment by mikebrow** [comment]
doesn't make sense... try make clean first?

**Comment by bg-chun** [comment]
@mikebrow 
I don't try `make clean` yet, I will try it.
Before, I usually delete `gopath`(~/go) then do `go get` again.
If `make clean` does not resolve this issue, I will try to build this package inside a docker container with golang image.

**Comment by bg-chun** [comment]
I found the reason, cri-plugin was disabled.
I just thought it is enabled by default, but it was not.

By default, CRI Messages is handled by docker-shim inside kubelet.
After i set a containerd as a default container runtime and enable cri-plugin, I can test with a newly built binary.

I refer the presentation to configure my node, thanks @Random-Liu , @fuweid 
https://youtu.be/pohiamd3PJM?t=1348
