### ISSUE TITLE
[WCOW] Support Container Compute Stats

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1275]
runhcs shim doesn't work container stats yet.

We should integrate it to support container compute stats when it is ready.

Ref https://github.com/microsoft/hcsshim/pull/695 and there will be PRs adding the actual implementation.

**Comment by Random-Liu** [comment]
https://github.com/containerd/containerd/pull/3775 is ready!

**Comment by Random-Liu** [comment]
We should evaluate the request time and overhead of the hcsshim stats call. See https://github.com/kubernetes/kubernetes/issues/82522

**Comment by jterry75** [comment]
Looks like it currently takes about ~1040 ms per stats query on a process container. I will take some traces and see what part is the biggest.

**Comment by jterry75** [comment]
Oh sorry. It takes 2ms. crictl issues two calls separated by 1 second. Each stats call takes ~2ms in total to complete.
