### ISSUE TITLE
Revisit IP selection order after IP dualstack is beta

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1278]
Currently we always prefer IPv4 over IPv6.

Based on https://github.com/kubernetes/kubernetes/blob/v1.16.0-rc.2/pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go#L611:
```
	// This - forced sort - could be avoided by checking which cidr that an IP belongs
	// to, then placing the IP according to cidr index. But before doing that. Check how IP is collected
	// across all of kubelet code (against cni and cri).
```

We should follow the decision about this in IP dualstack progress beta, and implement it the CRI plugin.

**Comment by mikebrow** [comment]
Good. Would be better if there was a way to pick which to prefer.

**Comment by oshoval** [comment]
Hi,
We are using k8s dual stack and Calico,
any unofficial suggested method please to make ipv6 the primary one, which is the one that podIP shows ?
(even disable_ipv4 in the node / pod / docker in case no other method exists, and this one is legit, trying it meanwhile)

**Comment by mikebrow** [comment]
@khenidak I looked over pending commits for https://github.com/kubernetes/kubernetes/pull/91824 and see that the diff for the TODO https://github.com/kubernetes/kubernetes/pull/91824/files#diff-fc2cc81fd1528b716e7ff3cebcd70db8R638-R646 is using the iplist order as the priority order..  for how to choose preference of ipv4 over ipv6.  How can that information be determined by the container runtime here: https://github.com/containerd/cri/blob/master/pkg/server/sandbox_run.go#L441 suggestions?

**Comment by mikebrow** [comment]
end result here was to 		
```
                // Create iptables handlers for both families, one is already created
 		// Always ordered as IPv4, IPv6
 		if primaryProtocol == utiliptables.ProtocolIPv4 {
 			ipt[0] = iptInterface
 			ipt[1] = utiliptables.New(execer, utiliptables.ProtocolIPv6)
```
which matches our implementation
