### ISSUE TITLE
[WCOW] Document how to setup windows dev/test environment

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1285]
Ref https://github.com/containerd/cri/issues/1257

We should have a document for this.

**Comment by PatrickLang** [comment]
Yeah - we need better building steps. I'm trying to cross-build and am having a lot of issues.

from containerd/containerd: `GOOS=windows make` will build containerd and ctr.exe, but it skips CRI plugin

containerd/containerd: `GOOS=windows make cri-release` fails

containerd/cri: `GOOS=windows make containerd` works
containerd/cri: `GOOS=windows make release` fails
