### ISSUE TITLE
[WCOW] SSH is flaky in windows test

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1288]
We setup ssh on windows using the script we wrote in kubernetes https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/testonly/install-ssh.psm1

However, it is pretty flaky, we occasionally see "Permission Denied" error.

We should fix it to avoid false signal.

**Comment by jterry75** [comment]
Is this for the stream server? Why do we need SSH?

**Comment by Random-Liu** [comment]
I think the problem is that we truncate the keys file and overwrite every 10 seconds:
```
New-Item -ItemType file -Force $user_keys_file | Out-Null
```

We should probably make that atomic.

> Is this for the stream server? Why do we need SSH?

This is only for testing. We use ssh to run test command remotely.

**Comment by jterry75** [comment]
Oh SSH not SSL. Why are we using SSH at all? Node configuration?

**Comment by yujuhong** [comment]
Yep retries are needed since it may take a while for the daemon to populate the keys.

**Comment by Random-Liu** [comment]
@yujuhong Sometimes, even one minute retry is not enough... https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1176273953686032384

Hope it doesn't happen too frequently. Let's see.
