### ISSUE TITLE
[WCOW] Revisit container hostname

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#1295]
Based on https://github.com/kubernetes/kubernetes/issues/82711#issuecomment-534621452, the hostname should be shared inside the network namespace.

However, it is currently not.

We sent https://github.com/containerd/cri/pull/1294 as a temporary fix, but we should follow up after  https://github.com/kubernetes/kubernetes/issues/82711 is fixed.

**Comment by PatrickLang** [comment]
@dineshgovindasamy - we talked about this a few weeks ago. I don't think the hostname is mirrored between containers, and needs to be set in CNI instead. If that's the case, then the #1294 fix is final. Can you confirm?

**Comment by PatrickLang** [comment]
cc @jterry75
