### ISSUE TITLE
Compile Error. build v1.11.1

### ISSUE THREAD

**Issue by wubo0067** [containerd/cri#1307]
build cmd:
go build -v -x -o ./containerd github.com/containerd/cri/cmd/containerd

Error info:
**go: k8s.io/kubernetes@v1.16.0 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0**

go version go1.13 linux/amd64

cri version: v1.11.1

**Comment by mikebrow** [comment]
our build command is "make" see the readme.md

**Comment by Random-Liu** [comment]
@wubo0067 It seems that you enabled go module by default?

We don't support `go mod` yet.

**Comment by wubo0067** [comment]
@Random-Liu @mikebrow ：Thank you so much！！

Yes，I use go module。

Compile ok with gopath
