### ISSUE TITLE
Remove NET_RAW capability and add net.ipv4.ping_group_range sysctl

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/cri#1308]
https://github.com/cri-o/cri-o/pull/2378

I assume this is not a breaking change for most users, but needs confirmation

**Comment by Random-Liu** [comment]
Is there a discussion in moby or Kubernetes about this somewhere?

**Comment by AkihiroSuda** [comment]
I think the Docker default will remain for compatibility.

Not sure this is discussed in SIG-node. Will ask in https://github.com/cri-o/cri-o/pull/2378

**Comment by AkihiroSuda** [comment]
CRI-O seems dropped CAP_SYS_CHROOT as well
https://github.com/cri-o/cri-o/pull/3119
