### ISSUE TITLE
Kubernetes cluster with containerd example needs updating containerd release.

### ISSUE THREAD

**Issue by PeriferalDevice** [containerd/cri#1317]
Hello!

When one is using the provided ansible playbooks there's problem that looks like copy of #856 
i.e. when running kubectl exec:

> error: unable to upgrade connection: error dialing backend: x509: certificate signed by unknown authority

The problem line is:
https://github.com/containerd/cri/blob/815f3e727de84cda4c74ac4324d6469d20df94f7/contrib/ansible/vars/vars.yaml#L2

I have checked things with 1.3.0 release variable set - no issues, it works fine (so far).

Also did check release/1.3 branch - same issue:
https://github.com/containerd/cri/blob/1fb415d208be37cbb2d3db52e56fe20126f9c116/contrib/ansible/vars/vars.yaml#L2

So I suggest to change vars.yaml to reflect release version. It shall work better for trying pure containerd with kubernetes.

**Comment by Random-Liu** [comment]
Thanks for this!

Actually the ansible setup might be out of date.

https://github.com/containerd/cri/blob/master/docs/kube-up.md might be easier to setup and more production ready.
