### ISSUE TITLE
Registry mirror fallback not working

### ISSUE THREAD

**Issue by awprice** [containerd/cri#1336]
We've noticed with the version of cri that is included with Containerd 1.3.0 that the fallback behaviour of resolving the image from the canonical source, e.g. registry-1.docker.io is no longer working. It does however work fine in 1.2.9.

We think this functionality is quite important when using mirrors, as it gives us a sense of reliability and fault tolerance in that if our mirror is not functioning/running we can still pull images from the canonical source.

We have our mirrors configured like so:
```toml
[plugins.cri.registry]
  [plugins.cri.registry.mirrors]
    [plugins.cri.registry.mirrors."docker.io"]
       endpoint = ["http://localhost:1234"]
```

On 1.2.9, if localhost:1234 was not functioning, cri would fallback to resolving the image from registry-1.docker.io. 

On 1.3.0 however, we see the following error:
```bash
# crictl pull ubuntu:18.04
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/ubuntu:18.04": failed to resolve reference "docker.io/library/ubuntu:18.04": failed to do request: Head http://localhost:1234/v2/library/ubuntu/manifests/18.04: dial tcp 127.0.0.1:1234: connect: connection refused 
```

I believe this change was due to the switch to containerd's RegistryHosts library introduced in https://github.com/containerd/cri/pull/1227. Looking at the code for this library, it will fail fast when the first host is unavailable. See https://github.com/containerd/containerd/blob/d7ec45b172d956575dbd195d809172095bc74bbb/remotes/docker/resolver.go#L274-L290 for code responsible for trying each host.

**Comment by Random-Liu** [comment]
@awprice I think this is a bug fix.

See here https://github.com/containerd/cri/issues/1201#issuecomment-514835772

**Comment by awprice** [comment]
@Random-Liu Not sure I follow, this should be fixed?

**Comment by Random-Liu** [comment]
I mean the new behavior is intended. The old behavior which blindly try next mirror is not.

**Comment by awprice** [comment]
cc @dmcgowan this is the issue I spoke to you in person about. You mentioned it should be acceptable to have some sort of fall back behaviour dependent on the error received.

**Comment by awprice** [comment]
Closing this out in favour of https://github.com/containerd/containerd/issues/3850
