### ISSUE TITLE
Parallels teardowns of pod network cause k8s flakiness

### ISSUE THREAD

**Issue by aojea** [containerd/cri#1352]
It turns out that the portmap plugin is not idempotent if it's called multiple times in parallel
https://github.com/containernetworking/plugins/issues/418

This cause that [kubernetes jobs running with KIND](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/85727/pull-kubernetes-e2e-kind-ipv6/1203740619378266115/artifacts/logs/kind-worker/kubelet.log) show a lot of errors related to this 

```
Dec 08 16:33:52 kind-worker kubelet[612]: E1208 16:33:52.590180     612 remote_runtime.go:128] StopPodSandbox "c9935e89d59fe7bbef3cd0abc408ebd3abe539e2661baa40abf0f784da93cc73" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "c9935e89d59fe7bbef3cd0abc408ebd3abe539e2661baa40abf0f784da93cc73": could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -X CNI-DN-cd6657f3c330fd2b2a3a6 --wait]: exit status 1: iptables: No chain/target/match by that name.
Dec 08 16:33:52 kind-worker kubelet[612]: E1208 16:33:52.590272     612 kuberuntime_manager.go:898] Failed to stop sandbox {"containerd" "c9935e89d59fe7bbef3cd0abc408ebd3abe539e2661baa40abf0f784da93cc73"}
Dec 08 16:33:52 kind-worker kubelet[612]: E1208 16:33:52.590342     612 kuberuntime_manager.go:676] killPodWithSyncResult failed: failed to "KillPodSandbox" for "6c17048a-7dc2-41d7-8273-e2d1c6c34b51" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"c9935e89d59fe7bbef3cd0abc408ebd3abe539e2661baa40abf0f784da93cc73\": could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -X CNI-DN-cd6657f3c330fd2b2a3a6 --wait]: exit status 1: iptables: No chain/target/match by that name.\n"
Dec 08 16:33:52 kind-worker kubelet[612]: E1208 16:33:52.590428     612 pod_workers.go:191] Error syncing pod 6c17048a-7dc2-41d7-8273-e2d1c6c34b51 ("pod-projected-configmaps-266265fc-9920-4e9c-ba76-40c027582004_projected-4056(6c17048a-7dc2-41d7-8273-e2d1c6c34b51)"), skipping: failed to "KillPodSandbox" for "6c17048a-7dc2-41d7-8273-e2d1c6c34b51" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"c9935e89d59fe7bbef3cd0abc408ebd3abe539e2661baa40abf0f784da93cc73\": could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -X CNI-DN-cd6657f3c330fd2b2a3a6 --wait]: exit status 1: iptables: No chain/target/match by that name.\n"
```

and a possible cause of flakiness due to the contention created and possible issues with the iptables locking mechanism https://github.com/kubernetes/kubernetes/pull/85727

Should this code use a lock to avoid trying to remove the pod network in parallel?

https://github.com/containerd/cri/blob/470776c903313f7946dab56a08d1bcef0495d974/pkg/server/sandbox_stop.go#L81

**Comment by Random-Liu** [comment]
@aojea Is this only a temporary error or permanent error?

**Comment by aojea** [comment]
> @aojea Is this only a temporary error or permanent error?

it happens permanently in kubernetes CI, I've found it in the [parallel e2e test jobs with KIND](https://testgrid.k8s.io/sig-testing-kind).
The main problem is that the portmap CNI plugin is not idempotent if executed in parallel https://github.com/containernetworking/plugins/issues/418#issuecomment-562974220

but I've opened this issue to know if is correct that containerd is executing `teardownPodNetwork` multiple times in parallel

**Comment by Random-Liu** [comment]
@aojea What CNI version are you using?

> it happens permanently in kubernetes CI

The teardown will be kept retried by kubelet and never succeed?

If you only see 1 or 2 times of this error for a particular pod in the kubelet log, it means that it will eventually get right.

**Comment by aojea** [comment]
The CNI are the reference plugins , portmap and ptp. https://github.com/containernetworking/plugins

From the logs it seems that containerd is executing the teardowns in parallel and this causes the portmap plugin to fail sometimes. Those failures are harmless because kubelet retries and eventually it gets right, but this seems to adds same flakiness to the jobs, not because of containerd or kubelet failures, because of iptables lock issues

**Comment by Random-Liu** [comment]
> My questions is if the teardowns from containerd should be done sequentially instead of in parallel

It should be done parallel. If anything breaks that, we should fix it.

**Comment by aojea** [comment]
Thanks for the clarifications, it was very helpful
Will close this and try to fix it in the portmap plugin https://github.com/containernetworking/plugins/pull/420

**Comment by squeed** [comment]
Just to close the loop, the CNI spec says that there can be concurrent operations on different containers, but that operations on the **same** container should be serialized.

So, if there's any chance that cri-containerd is doing this, then it's a bug. Otherwise, it's a plugin problem.

**Comment by aojea** [comment]
> Just to close the loop, the CNI spec says that there can be concurrent operations on different containers, but that operations on the **same** container should be serialized.
> 
> So, if there's any chance that cri-containerd is doing this, then it's a bug. Otherwise, it's a plugin problem.

@Random-Liu do you think I should reopen based on this comment ^^^?
