### ISSUE TITLE
can not pull image from http or insecure https in same registry domain

### ISSUE THREAD

**Issue by yylt** [containerd/cri#1421]
Hi, there is a question

docker pull will try from http and https protocol, but cri plugin will not, and i write configure file will not work

```
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."hub.xx.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."hub.xx.io".tls]
            insecure_skip_verify = true
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."hub.xx.io"]
          endpoint = ["https://hub.xx.io","http://hub.xx.io"]
    [plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
```

Could you  support http and https from same registry, and pull from registry by http protocol will not check tls  even if tls config had set.

**Comment by fuweid** [comment]
Hi, does option `insecure_skip_verify` help?

```
[plugins.cri.registry.configs."my.custom.registry".tls]
  insecure_skip_verify = true
```

https://github.com/containerd/cri/pull/1346/commits

**Comment by yylt** [comment]
`insecure_skip_verify` can only help skip tls check, and cri will ont use http.

In my case, `docker pull` work good, but when migrate to containerd(v1.3.3) runtime, `crictl pull` can not work

https://github.com/containerd/cri/blob/5fb103d8e66f0c6292971b00f05b2aed4c99f902/pkg/server/image_pull.go#L322

In this line, it will failed if there are tls config when use http protocol

**Comment by fuweid** [comment]
Sorry @yylt for the late reply. If you are using http, why add tls for toml?

**Comment by mikebrow** [comment]
note: moving to what will "hopefully" be more docker like config for containerd & containerd/cri config ->  https://github.com/containerd/containerd/pull/4138

**Comment by yylt** [comment]
I just want it  like docker to pull image, and I don't understand why to judge it is incorrect to use http scheme and certificate configure at one time

@mikebrow the PR more like want to use self-signed certificate

**Comment by mikebrow** [comment]
> I just want it like docker to pull image, and I don't understand why to judge it is incorrect to use http scheme and certificate configure at one time
> 
> @mikebrow the PR more like want to use self-signed certificate

I understand.. just pointing out it should be more configurable soon via upcoming changes to containerd config that will be replacing the containerd/cri config that will be deprecated soon.

Of course we could also drop a change to the api to allow tls to be configured and "ignored" for http. The reason for the test is non-experts might get the wrong impression that their http insecure connection is secured by adding tls to the config. In your case you want to be insecure first, then try https with tls. But the kubernetes "way" is secure by default. Thus the conflict of opinion on how this should work. 

Maybe we can push out a warning message and let the code continue on without returning error.  Let me digest this a bit.  Maybe @Random-Liu will want to chime in on this one :-)

**Comment by joedborg** [comment]
Not sure if this is linked to https://github.com/containerd/cri/issues/1367 and or https://github.com/containerd/cri/issues/1201 but I still get the error:


```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."184.73.131.126:5000"]
  endpoint = ["http://184.73.131.126:5000"]
```

```
Events:
  Type     Reason     Age        From                       Message
  ----     ------     ----       ----                       -------
  Normal   Scheduled  <unknown>  default-scheduler          Successfully assigned default/test to ip-172-31-43-150
  Normal   Pulling    6s         kubelet, ip-172-31-43-150  Pulling image "184.73.131.126:5000/nginx:latest"
  Warning  Failed     6s         kubelet, ip-172-31-43-150  Failed to pull image "184.73.131.126:5000/nginx:latest": rpc error: code = Unknown desc = failed to pull and unpack image "184.73.131.126:5000/nginx:latest": failed to resolve reference "184.73.131.126:5000/nginx:latest": failed to do request: Head https://184.73.131.126:5000/v2/nginx/manifests/latest: http: server gave HTTP response to HTTPS client
  Warning  Failed     6s         kubelet, ip-172-31-43-150  Error: ErrImagePull
  Normal   BackOff    6s         kubelet, ip-172-31-43-150  Back-off pulling image "184.73.131.126:5000/nginx:latest"
  Warning  Failed     6s         kubelet, ip-172-31-43-150  Error: ImagePullBackOff

```

**Comment by mikebrow** [comment]
> `insecure_skip_verify` can only help skip tls check.
> 
> In my case, `docker pull` work good, but when migrate to containerd(v1.3.3) runtime, `crictl pull` can not work
> 
> https://github.com/containerd/cri/blob/5fb103d8e66f0c6292971b00f05b2aed4c99f902/pkg/server/image_pull.go#L322
> 
> In this line, it will failed if there are tls config when use http protocol
> 
> It is expected that `crictl pull` should try registry writed in endpoints and skip tls config check when use http

@yylt try on master if you can...

**Comment by yylt** [comment]
> > `insecure_skip_verify` can only help skip tls check.
> > In my case, `docker pull` work good, but when migrate to containerd(v1.3.3) runtime, `crictl pull` can not work
> > https://github.com/containerd/cri/blob/5fb103d8e66f0c6292971b00f05b2aed4c99f902/pkg/server/image_pull.go#L322
> > 
> > In this line, it will failed if there are tls config when use http protocol
> > It is expected that `crictl pull` should try registry writed in endpoints and skip tls config check when use http
> 
> @yylt try on master if you can...

thank you
