### ISSUE TITLE
Kubernetes Calico no ip

### ISSUE THREAD

**Issue by StodaraHodan** [containerd/cri#1432]
I am trying to setup a k8s cluster (1.18) with containerd (1.2.13) and calico (3.13.2).
OS: debian 10

with docker runtime engine everything works fine but containerd gives me this error in the coredns and calico controller pods after initiating the kluster with kubeadm and deploying the calico manifest

` Warning  FailedCreatePodSandBox  34s                   kubelet, <hostname>  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ecb0f69131e5f6be3bbf5278f09495008b50f5c93cce9386088cf84be3f99129": error getting ClusterInformation: Get https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: Service Unavailable`

it seems that the pod network just isn't able to start, so none of these pods get an ip from the pod network.

i tried to get all the configuration according to the official kubernetes documentation and here on github.
i also found the ansible playbook here in this project and tried to apply the steps manually on by debian machine.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
https://kubernetes.io/docs/setup/production-environment/container-runtimes/
https://github.com/containerd/cri/blob/master/docs/installation.md

I'm actually really confused on how containerd / cni has to be configured.

Any insight would be helpful

This is my /etc/containerd/config.toml:

```
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.cgroups]
    no_prometheus = false
  [plugins.cri]
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    enable_selinux = false
    sandbox_image = "k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    disable_proc_mount = false
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      no_pivot = false
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = ""
        runtime_root = ""
      [plugins.cri.containerd.untrusted_workload_runtime]
        runtime_type = ""
        runtime_engine = ""
        runtime_root = ""
    [plugins.cri.cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      conf_template = ""
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
    [plugins.cri.x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""
  [plugins.diff-service]
    default = ["walking"]
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins.opt]
    path = "/opt/containerd"
  [plugins.restart]
    interval = "10s"
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
```

**Comment by mikebrow** [comment]
Can you run containerd in level = debug mode... I'd like to see the detail for the CNI result.

**Comment by StodaraHodan** [comment]
Hi, thanks for the reply, i started containerd with level = "debug"
at first sight, i couldn't find anything wrong other than no ip is assigned to the calico containers
[cdlog.txt](https://github.com/containerd/cri/files/4473985/cdlog.txt)

**Comment by StodaraHodan** [comment]
I can also see that both the calico-node container and the host have this tunnel interface (podnetwork range: i chose 10.1.0.0/16)

```
3: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.1.189.128/32 brd 10.1.189.128 scope global tunl0
```

**Comment by StodaraHodan** [comment]
found the problem: https://github.com/projectcalico/calico/issues/2941
