### ISSUE TITLE
Send X-Forwarded-Host when using wildcard mirror

### ISSUE THREAD

**Issue by dmayle** [containerd/cri#1434]
Now that CRI supports a wildcard header for mirrors, we can have a problem implementing a pull through cache because of the ambiguity of the requested host (two different images with the same name on different backing registries).  It also requires configuring the pull through cache to check all possible registries, since it does not know where the original image should be sourced.

If CRI were to set the X-Forwarded-Host header on the request, we could use that to solve both problems.

**Comment by dmcgowan** [comment]
See https://github.com/containerd/containerd/issues/3734

This needs to be implemented in the containerd libraries and done in a consistent way. Closing this one as it is tracked already in containerd and [OCI distribution spec](https://github.com/opencontainers/distribution-spec/pull/66).
