### ISSUE TITLE
Get rid of nsenter and socat

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#144]
Currently we are using nsenter for both CNI plugin and port forword.

Ideally, we should be able to use `NetNS.Do` to run code inside a specific network namespace.

However, golang has an issue that it may spawn new threads from locked thread, which will inherit the network namespace. https://github.com/golang/go/issues/20676

We should be able to get rid of all nsenters after this is fixed.

**Comment by Random-Liu** [comment]
Also ref https://github.com/kubernetes-incubator/cri-containerd/pull/139.

**Comment by abhinandanpb** [comment]
The other option would be to use ```ip netns exec``` provided we have our network namespaces created under ```/var/run/netns/....```

**Comment by cpuguy83** [comment]
Or alternatively could setup a container to do this work... of course any option still requires execing a new process until go1.10 lands.

**Comment by Random-Liu** [comment]
golang 1.10 is released, golang/go#20676 should have been fixed.

We can get rid of `nsenter` and `socat` after switch to golang 1.10.

**Comment by tkellen** [comment]
:tada:

**Comment by Random-Liu** [comment]
We plan to cut an early `rc.1` release today to carry several fix and improvement. Move this to `rc.2`.
