### ISSUE TITLE
Pass pod annotations as extra args to CNI plugins

### ISSUE THREAD

**Issue by chiragtayal** [containerd/cri#1452]
Pass the annotations as extra arguments to the CNI plugins and thereby allowing the custom CNI plugins to make decisions based on the additional metadata about the POD.

Detailed [discussion](https://github.com/kubernetes/kubernetes/issues/69882) about adding annotations extra arguments

**Comment by dims** [comment]
@chiragtayal the PR into dockershum was not merged AFAICT - https://github.com/kubernetes/kubernetes/pull/81583

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/issues/69882 is still an open issue.

**Comment by chiragtayal** [comment]
@dims my bad, yes PR is not merged yet and issue is still open. I have removed that PR line from issue.

We have a custom CNI plugin which require extra information from the pod in addition to current Args passed to the plugin. 

It is possible to get around this problem but it is very expensive in large kubernetes cluster. I can use kubernetes clientSet to get the pod data, but that requires CNI plugin to call api server for each POD creation, which increase traffic in large clusters and load on apiserver.

With this feature we want to have a mechanism where user can choose to pass pod annotations  as labels to the CNI plugin, and CNI plugin can choose to ignore the information without error

**Comment by dims** [comment]
@chiragtayal the right thing to do is to write a KEP for kubernetes as @danwinship mentions here:
https://github.com/kubernetes/kubernetes/pull/81583#issuecomment-565483802

As that will help all CRI's. Once that's done in kubelet if there are things to do here in the CRI, we can visit that then. sounds good?
