### ISSUE TITLE
Expose ptrace-related hardening of containers in LinuxContainerSecurityContext

### ISSUE THREAD

**Issue by sargun** [containerd/cri#1453]
One mechanism to harden a container from its neighbors is to set `PR_SET_DUMPABLE` to 0. This makes it so that even if the yama scope is setup to be widely accessible, it is not possible to ptrace it (or poke at it's /proc too much) from other sibling processes.

It is difficult to "get this right" in container code, as there's a race between the time the container starts and you call the prctl. In the interim period, ptrace could have been called, and parasitic code could be injected. Therefore, this needs the assistance of the container runtime.

**Comment by dims** [comment]
cc @justincormack @thaJeztah

**Comment by justincormack** [comment]
To get this exposed in CRI it would have to be defined in OCI first I would think.

**Comment by dims** [comment]
@justincormack what would be the closest equivalent field in the OCI (runtime spec?)

**Comment by justincormack** [comment]
No new privileges, which is another prctl flag is set in Linux specific process flags https://github.com/opencontainers/runtime-spec/blob/39c287c415bf86fb5b7506528d471db5405f8ca8/config.md#linux-process which makes some sense, so adding another boolean for dumpable here seems reasonable (although perhaps inverted for compat, so it is "undumpable" so empty does not change behaviour?)

**Comment by dims** [comment]
Got it. looks like we pass that through to runc here:
https://github.com/containerd/cri/blob/9d37687a9569775b0bf38fe478ba1a3557b9496c/pkg/server/container_create_unix.go#L190-L192

and runc actually calls Prctl:
https://github.com/opencontainers/runc/blob/master/libcontainer/setns_init_linux.go#L61
