### ISSUE TITLE
Apparently inconsistent docs regarding plugins and cri

### ISSUE THREAD

**Issue by dsyer** [containerd/cri#1460]
In https://github.com/containerd/cri/blob/master/docs/config.md we see `plugins."io.containerd.grpc.v1.cri".registry` and in https://github.com/containerd/cri/blob/master/docs/registry.md we see `plugins.cri.registry`. So if both are right it's confusing, and maybe needs to be clarified. But when I tried the `plugins.cri.registry` form everything seemed to break, so maybe it's actually a typo, or hangover from an older document? I also noticed that `crictl info` and `containerd config default` print the `"io.containerd.grpc.v1.cri"` form.

**Comment by AkihiroSuda** [comment]
The long form requires `version = 2` header.
