### ISSUE TITLE
Failed to run critest v1.18.0

### ISSUE THREAD

**Issue by zhsj** [containerd/cri#1461]
```
[k8s.io] AppArmor
/home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support apparmor
  /home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:69
    should fail with with an unloaded profile [It]
    /home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:84

    Expected an error to have occurred.  Got:
        <nil>: nil

    /home/sascha/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/apparmor_linux.go:131
```

critest v1.18.0 changes the logic for `should fail with with an unloaded profile` in https://github.com/kubernetes-sigs/cri-tools/pull/576

Previously it expects the container status is not running.
https://github.com/kubernetes-sigs/cri-tools/commit/2d29d64a0185523d78a9fad7dc3d6dcd4dc0dc7b#diff-f4cc9be3660927f0b0e0423a71ec7753L138

Now it expects the container to fail to create, the containerdID is empty
https://github.com/kubernetes-sigs/cri-tools/commit/2d29d64a0185523d78a9fad7dc3d6dcd4dc0dc7b#diff-f4cc9be3660927f0b0e0423a71ec7753R87

And it seems cri and containerd don't check the non existent profile.
https://github.com/containerd/cri/blob/14c4b47bb1106dd1f714206cf24061f814e74b2e/pkg/server/container_create_unix.go#L356
https://github.com/containerd/containerd/blob/36952e989a8e25ca7b21e6abf89fff91ab9c0028/contrib/apparmor/apparmor.go#L35

**Comment by mikebrow** [comment]
true we (cri/containerd) don't check whether the profile exists we make sure it has the correct prefix name, remove the prefix name and place it into the container spec process apparmor field per request by the caller.. passing it through to runc.

I'm not sure we should change this well established behavior at the container runtime layer. There are many spec fields that we do not validate in the container runtimes.. we simply pass them through to the runtime per request. I would've expected a failure to occur in runc or at least in the OS when the profile did not exist. Looking further.. runc just passes it along as requested to the new libcontainer.Process runc also does no validation on the requested apparmor profile...

**Comment by mikebrow** [comment]
Looks like there is an expectation for a failed to load error https://kubernetes.io/docs/tutorials/clusters/apparmor/

maybe some docker check behavior?

**Comment by feiskyer** [comment]
so doesn't this means when a wrong profile is set, containerd still runs good without any errors? seems throwing out an error is more reasonable

**Comment by mikebrow** [comment]
Hmm.. 

How would I know if the wrong profile was set?

**Comment by zhsj** [comment]
> > so does this mean when a wrong profile is set, containerd still runs good without any errors? seems throwing out an error is more reasonable
> 
> Hmm..
> 
> How would I know if the wrong profile was set?
> 

I think just checking the profile name in /sys/kernel/security/apparmor/profiles.
https://github.com/containerd/containerd/blob/master/contrib/apparmor/template.go#L189

**Comment by mikebrow** [comment]
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ sudo aa-status
apparmor module is loaded.
27 profiles are loaded.
27 profiles are in enforce mode.
   /sbin/dhclient
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince//sanitized_helper
   /usr/bin/lxc-start
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/lightdm/lightdm-guest-session
   /usr/lib/lightdm/lightdm-guest-session//chromium
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
   /usr/sbin/ippusbxd
   /usr/sbin/tcpdump
   docker-default
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
   webbrowser-app
   webbrowser-app//oxide_helper
0 profiles are in complain mode.
4 processes have profiles defined.
4 processes are in enforce mode.
   /sbin/dhclient (905) 
   /usr/sbin/cups-browsed (28923) 
   /usr/sbin/cupsd (28922) 
   /usr/sbin/cupsd (28930) 
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri$ sudo ls /sys/kernel/security/apparmor/profiles
/sys/kernel/security/apparmor/profiles
```
hmm.. ^ :-)

**Comment by mikebrow** [comment]
Thx for the help @zhsj thx for the reply @feiskyer fix here: https://github.com/containerd/cri/pull/1464

**Comment by fuweid** [comment]
ping @zhsj the fix has been merged. could you help to verify this? Thanks!

**Comment by zhsj** [comment]
> ping @zhsj the fix has been merged. could you help to verify this? Thanks!

Since the critest is also bumped to 1.18.0 in the PR, so it's good now.
