### ISSUE TITLE
[Question] How to set the namespace for the project using CRI?

### ISSUE THREAD

**Issue by chendave** [containerd/cri#1471]
I haven't set any namespace for the project which using containerd CRI to create container, but it is using "k8s.io" by default, 

```bash
# ctr --namespace=k8s.io container ls
CONTAINER                                                           IMAGE                                                                      RUNTIME
0aa419b51081aa31ffdbc4a0a24664712ede129277cc71bd9b71bc8a89e29780    sha256:f6d22dec9931b638b2f67c7197732e2bd1b9311877c2d7a1df7136f952fe8fc7    io.containerd.runtime.v1.linux
850784fcac0cb93de64159cf6e46c7d07b0e8f807838596a9fad02b9095a6299    sha256:f6d22dec9931b638b2f67c7197732e2bd1b9311877c2d7a1df7136f952fe8fc7    io.containerd.runtime.v1.linux
d447de8e711073a4c196c41bb9625ddac11208dc445fc9ac46173c6e93470f00    sha256:f6d22dec9931b638b2f67c7197732e2bd1b9311877c2d7a1df7136f952fe8fc7    io.containerd.runtime.v1.linux
f1d4190e1bd584bfee8d3bac13c9aca7b0520ecc5695fb5d39eb6e665932d9c2    k8s.gcr.io/pause:3.1                                                       io.containerd.runtime.v1.linux
```

I searched from the code base and looks like the namespace is set in this way,
https://github.com/containerd/cri/blob/65830369b6b2b4edc454bf5cebbd9b76c1c1ac66/pkg/containerd/util/util.go#L43-L46

and the `constants.K8sContainerdNamespace` is defined as "k8s.io". 

Is there anyway for us to override this behavior, since not all the projects using the CRI is kuberentes  although it might based on some methods imported by kubernetes.

Thanks!

**Comment by dweomer** [comment]
CRI does not honor any containerd namespace, you only get `k8s.io`. I have a PR that makes CRI multi-namespace #1462

**Comment by chendave** [comment]
> CRI does not honor any containerd namespace, you only get `k8s.io`. I have a PR that makes CRI multi-namespace #1462

Thank you Jacob for your quick response! so with your patch merged how can I set which namespace those containers will go for the project using CRI?

**Comment by dweomer** [comment]
A client setup using WithDefaultNamespace() ought to work.
