### ISSUE TITLE
Use `repo-infra` when it is ready for our use case.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#15]
https://github.com/kubernetes/repo-infra is great tool.

Now we copied the boilerplate verification part into the repo, but removed the other go code verification.

It would be better to consolidate this in the future and only use `repo-infra` when it is ready for our use case.

Several related issue:
1) https://github.com/kubernetes/repo-infra/issues/15
2) https://github.com/kubernetes/repo-infra/issues/12
3) We don't need the build part now.
4) Subtree the repo causes DCO problem.
  * If we squash commits, @mikebrow found that he could not sign the squashed commit.
  * If we don't squash, that will be quite spammy.

**Comment by Random-Liu** [comment]
@mikebrow Do you think we can close this one? We've done so much without repo-infra. :)

**Comment by mikebrow** [comment]
Let's leave it open for now I'll investigate.   I need to sync our fixes back to repo infra first though :-)
