### ISSUE TITLE
Need a switch to disable hard enforce of huge page limits (legacy issue)

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#1500]
https://github.com/kubernetes-sigs/kind/issues/1637#issuecomment-636855802

initial issue resolved...

Is now a documentation issue to explain which releases have support, the default option for filtering where the limits are not supported, and enabling hard errors if not supported.

**Comment by dims** [comment]
working on a fix in https://github.com/containerd/cri/pull/1501

**Comment by mikebrow** [comment]
leaving this issue open till we have documented the current lack of support for huge page limits in prior releases.

**Comment by dims** [comment]
@mikebrow are we happy where we have the flag currently? which docs should i fix up?

**Comment by mikebrow** [comment]
needs a couple lines here:
https://github.com/containerd/cri/blame/master/docs/config.md#L84

This will explain the option in containerd config default:
```
    tolerate_missing_hugepages_controller = true
```

We don't have a table for support (or non) of such features.. have to think about that. But if we did it should probably go here (or at least be referenced from here):
https://github.com/containerd/cri#support-metrics

We'll want to highlight this change for the next containerd/containerd 1.4 release with a release note blurb.  Can draft the release note text in this docs update or add it to #1501.

**Comment by AkihiroSuda** [comment]
Now we have the flag:
```toml
  # tolerate_missing_hugetlb_controller if set to false will error out on create/update
  # container requests with huge page limits if the cgroup controller for hugepages is not present.
  # This helps with supporting Kubernetes <=1.18 out of the box. (default is `true`)
  tolerate_missing_hugetlb_controller = true
```
https://github.com/containerd/cri/blob/master/docs/config.md
