### ISSUE TITLE
Release tarballs for v1.3.5 and v1.3.6 not published

### ISSUE THREAD

**Issue by hakman** [containerd/cri#1518]
As described in the release process doc, tarballs for each releases should be pushed to https://storage.googleapis.com/cri-containerd-release/.
https://github.com/containerd/cri/blob/master/docs/release.md#step-5-publish-release-tarball-for-kubernetes

At the moment, there are no such tarballs for version 1.3.5:
https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.3.5.linux-amd64.tar.gz
https://storage.googleapis.com/cri-containerd-release/cri-containerd-cni-1.3.4.linux-amd64.tar.gz

/cc @Random-Liu

**Comment by hakman** [comment]
Same thing for version 1.3.6.

**Comment by strigazi** [comment]
+1 @hakman , I was about to create an issue for this.

I would be great if we had the 1.4.0 beta releases to start testing the official releases.
https://github.com/containerd/containerd/releases/tag/v1.4.0-beta.1

It looks like the release is done by someone with write access to the gcs bucket.
Maintainers, if we can help with PR let us know.

**Comment by kfox1111** [comment]
I didn't notice we were not getting updates because our automation currently looks for new tarballs from https://storage.googleapis.com/cri-containerd-release/cri-containerd-$VER.linux-amd64.tar.gz

The tarball includes the right version of runc, as well as a systemd unit file. These are very useful for deployment. What needs to be done to get newer releases?

**Comment by estesp** [comment]
We are working to add that logic and bundle to our new GitHub Actions release workflow to replace the previous process where it was being published to a GCS bucket. We hope to have it in place for 1.4.0 and then can apply it to 1.3 as needed.

**Comment by hakman** [comment]
@estesp Would it be possible or desirable to fix https://github.com/containerd/containerd/issues/4378 in the mean time?
For me, the main blocker is that `runc` is missing from the GH release package.
Thanks a lot for responding. This has been a blocker for bundling newer contained releases in Kops and the update is much appreciated.

**Comment by AkihiroSuda** [comment]
runc binary is available here: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc91

**Comment by hakman** [comment]
@AkihiroSuda I see that for the 1.3 branch runc is set to v1.0.0-rc10, but for 1.4 the tag is a bit newer than v1.0.0-rc91.
https://github.com/containerd/containerd/blob/v1.4.0-rc.0/vendor.conf#L34

My point is that it is both more convenient for users and also safer to bundle the right runc version. This way if someone forgets to install the latest / matching version doesn't get into trouble.

**Comment by estesp** [comment]
We're in the process of fixing the missing "full" tarballs for the 1.4.0 release; see [this comment](https://github.com/containerd/containerd/issues/4378#issuecomment-672364617). Once we validate this, we can apply the same fixes for `release/1.3`

**Comment by hakman** [comment]
Thanks for the update @estesp. Looking forward to try 1.4.0.
