### ISSUE TITLE
Pods stuck in container creating on enabling CNI chaining

### ISSUE THREAD

**Issue by jayanthvn** [containerd/cri#1544]
**Pods stuck in container creating on enabling CNI chaining**
Hi,
 
We recently tried adding CNI chaining to support the upstream bandwidth plugin to the [`amazon-vpc-cni-k8s`](https://github.com/aws/amazon-vpc-cni-k8s/). In the interface list sent with the CNI result we add the pod veth interface ("eni" is the prefix for legacy reasons) and this works fine with Docker but pods get stuck in container creating when using `containerd`. We can see that the `amazon-vpc-cni-k8s` CNI plugin has responded back with an interface name, but it is getting a delete immediately after a create sandbox. On further debugging looks like if the veth interface name (`eni****`) in the interface list is replaced with `“eth0”` then everything works fine. Even if we add the interface list to have veth and eth0 but if interface index points to veth we see the same issue.Looks like only `eth*` is recognized.
 
```
// Interface chained with veth
 
	interfaceIndex := 0
	ips := []*current.IPConfig{
		{
			Version: "4",
			Address: *addr,
				Interface: &interfaceIndex,
		},
	}
 
	result := &current.Result{
		IPs: ips,
		     Interfaces: []*current.Interface{ {Name: hostVethName}},
	}
 
```
CONTAINERD LOGS -
 
```
Jul 18 01:01:01 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: time="2020-07-18T01:01:01.869879024Z" 
level=debug msg="Sandbox config &PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:my-nginx-75897978cd-zgd4g,Uid:57ab2751-e517-4efc-a7bd-2cde21d2b4aa,Namespace:default,Attempt:0,},Hostname:my-nginx-75897978cd-zgd4g,LogDirectory:/var/log/pods/default_my-nginx-75897978cd-zgd4g_57ab2751-e517-4efc-a7bd-2cde21d2b4aa,
DnsConfig:&DNSConfig{Servers:[10.100.0.10],
Searches:[default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal],Options:[ndots:5],},PortMappings:[]*PortMapping{&PortMapping{Protocol:TCP,ContainerPort:80,HostPort:0,HostIp:,},},
Labels:map[string]string{io.kubernetes.pod.name: my-nginx-75897978cd-zgd4g,io.kubernetes.pod.namespace: default,io.kubernetes.pod.uid: 57ab2751-e517-4efc-a7bd-2cde21d2b4aa,pod-template-hash: 75897978cd,run: 
my-nginx,},Annotations:map[string]string{kubernetes.io/config.seen: 2020-07-16T17:09:07.878948380Z,kubernetes.io/config.source: api,kubernetes.io/psp: eks.privileged,},
Linux:&LinuxPodSandboxConfig{CgroupParent:/kubepods/besteffort/pod57ab2751-e517-4efc-a7bd-2cde21d2b4aa,
SecurityContext:&LinuxSandboxSecurityContext{NamespaceOptions:&NamespaceOption{Network:POD,Pid:CONTAINER,Ipc:POD,},SelinuxOptions:nil,RunAsUser:nil,ReadonlyRootfs:false,SupplementalGroups:[],Privileged:false,SeccompProfilePath:,RunAsGroup:nil,},
Sysctls:map[string]string{},},}"

Jul 18 01:01:01 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: time="2020-07-18T01:01:01.869934230Z" 
level=debug msg="Generated id \"80fda3118d1824b6368397f1e702c90240a96c9ed667cf9f1f99eb4f01b4836c\" for sandbox \"my-nginx-75897978cd-zgd4g_default_57ab2751-e517-4efc-a7bd-2cde21d2b4aa_0\""

Jul 18 01:01:01 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: time="2020-07-18T01:01:01.870028329Z" level=debug msg="
Use OCI {Type:io.containerd.runc.v1 Engine: PodAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false} for sandbox \"80fda3118d1824b6368397f1e702c90240a96c9ed667cf9f1f99eb4f01b4836c\""

Jul 18 01:01:02 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: {"level":"info","ts":"2020-07-18T01:01:02.159Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"CNI Plugin version: v1.7-rc-mac-dirty ..."}
```
————>`amazon-vpc-cni-k8s` CNI plugin sent eni but appended Eth0 IPconfig is NULL since CNI sent just the IP for eni.
 
```
**Jul 18 01:01:02 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: time="2020-07-18T01:01:02.198262083Z" 
level=debug msg="cni result for sandbox \"80fda3118d1824b6368397f1e702c90240a96c9ed667cf9f1f99eb4f01b4836c\": {\"Interfaces\":{\"eni04894926c85\":
{\"IPConfigs\":[{\"IP\":\"192.168.49.3\",\"Gateway\":\"\"}],\"Mac\":\"\",\"Sandbox\":\"\"},\"
eth0\":{\"IPConfigs\":null,\"Mac\":\"\",\"Sandbox\":\"\"},\"lo\":{\"IPConfigs\":[{\"IP\":\"127.0.0.1\",\"Gateway\":\"\"},{\"IP\":\"::1\",\"Gateway\":\"\"}],
\"Mac\":\"00:00:00:00:00:00\",\"Sandbox\":\"/var/run/netns/cni-d626aa8d-e55a-fa9e-e69a-c4cac718da59\"}},
\"DNS\":[{},{}],\"Routes\":null}"**  
```

It is failing here -
```
https://github.com/containerd/cri/blob/98aadbbe56369ebafa03b6e08ad53859580313f1/pkg/server/sandbox_run.go#L342
```

PLUGIN LOGS -
 
```
{"level":"debug","ts":"2020-07-18T01:01:02.161Z","caller":"routed-eni-cni-plugin/cni.go:189",
"msg":"SetupNS: hostVethName=eni04894926c85, contVethName=eth0, 
netnsPath=/var/run/netns/cni-d626aa8d-e55a-fa9e-e69a-c4cac718da59, table=2, mtu=9001"}

{"level":"debug","ts":"2020-07-18T01:01:02.193Z","caller":"driver/driver.go:173","
msg":"SetupNS: disabled IPv6 RA and ICMP redirects on eni04894926c85"}

{"level":"debug","ts":"2020-07-18T01:01:02.193Z","caller":"driver/driver.go:173",
"msg":"Setup host route outgoing hostVeth, LinkIndex 26013"}

{"level":"debug","ts":"2020-07-18T01:01:02.193Z","caller":"driver/driver.go:173",
"msg":"Successfully set host route to be 192.168.49.3/0"}

{"level":"info","ts":"2020-07-18T01:01:02.194Z","caller":"driver/driver.go:173",
"msg":"Added toContainer rule for 192.168.49.3/32"}

{"level":"info","ts":"2020-07-18T01:01:02.194Z","caller":"driver/driver.go:173",
"msg":"Successfully added pod rule[ip rule 1536: from 192.168.49.3/32 table 2] to 192.168.0.0/16"}

{"level":"info","ts":"2020-07-18T01:01:02.194Z","caller":"routed-eni-cni-plugin/cni.go:118","msg":
"RESULT - Interfaces:[{Name:eni04894926c85 Mac: Sandbox:}], 
IP:[{Version:4 Interface:0xc000184b88 Address:{IP:192.168.49.3 Mask:ffffffff} Gateway:<nil>}], 
DNS:{Nameservers:[] Domain: Search:[] Options:[]}"}
```
 
Is there any limitation to always use interface prefixed with eth* ?
 
```
// Initializes library
	l, err := gocni.New(
		// one for loopback network interface
		gocni.WithMinNetworkCount(2),
		gocni.WithPluginConfDir("/etc/cni/net.d"),
		gocni.WithPluginDir([]string{"/opt/cni/bin"}),
		// Sets the prefix for network interfaces, eth by default
		gocni.WithInterfacePrefix(ifPrefixName))
	if err != nil {
		log.Fatalf("failed to initialize cni library: %v", err)
	}
```
```
	result, err := c.netPlugin.Setup(ctx, id, path, opts...)
	if err != nil {
		return err
	}
	logDebugCNIResult(ctx, id, result)
	// Check if the default interface has IP config
	if configs, ok := result.Interfaces[defaultIfName]; ok && len(configs.IPConfigs) > 0 {
		sandbox.IP, sandbox.AdditionalIPs = selectPodIPs(configs.IPConfigs)
		sandbox.CNIResult = result
		return nil
	}
```
 
*****
But if we return `eth0` instead, then the IP is populated fine, but the bandwidth plugin won't work correctly.
 
```
result := &current.Result{
		IPs: ips,
		     Interfaces: []*current.Interface{ {Name: "eth0"}},
	}
```
```
Jul 18 21:41:16 ip-192-168-56-112.us-west-2.compute.internal containerd[19660]: time="2020-07-18T21:41:16.064574904Z" 
level=debug msg="cni result for sandbox \"e17e3cb35f0a90171bf83a00540f429ba8c7812edff12191dbcc35a7b94dfdf2\": 
{\"Interfaces\":{\"eth0\":{\"IPConfigs\":[{\"IP\":\"192.168.43.84\",\"Gateway\":\"\"}],\"Mac\":\"\",\"Sandbox\":\"\"},
\"lo\":{\"IPConfigs\":[{\"IP\":\"127.0.0.1\",\"Gateway\":\"\"},
{\"IP\":\"::1\",\"Gateway\":\"\"}],\"Mac\":\"00:00:00:00:00:00\",\"
Sandbox\":\"/var/run/netns/cni-b79f80f9-15e6-40b8-f669-48d233bd56ab\"}},\"DNS\":[{},{}],\"Routes\":null}"
```

**Steps to reproduce the issue:**
1. enable interface chaining on aws-vpc-cni-k8s (https://github.com/aws/amazon-vpc-cni-k8s/pull/1029)
2. start a pod

**Describe the results you received:**
Pods stuck in container creating.

**Describe the results you expected:**
Pods should be created with the IP returned by the CNI plugin.

**Output of `containerd --version`:**

```
containerd --version
containerd github.com/containerd/containerd 1.3.2 ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
```

**Comment by jayanthvn** [comment]
As a temporary solution, I made CNI to send list of interface - [eni***, eth0] and IP address list and that is working fine since this time go-cni was able to find IP for eth0 and the check in setupPodNetwork passed. Is it possible to remove the limitation of always having defaultIfname as "eth0" similar to dockershim.

```
level=debug msg="cni result for sandbox \"c5c9a65fdef5beb3a00ae8cf10425e423829f2d27481a0d5ec6046ec4b4826f0\": 
{\"Interfaces\":{\"enibb2235a4e2c\":{\"IPConfigs\":
[{\"IP\":\"192.168.73.126\",\"Gateway\":\"\"}],\"Mac\":\"\",\"Sandbox\":\"\"},\"eth0\":{\"IPConfigs\":
[{\"IP\":\"192.168.73.126\",\"Gateway\":\"\"}],\"Mac\":\"\",\"Sandbox\":\"\"},\"lo\":{\"IPConfigs\":
[{\"IP\":\"127.0.0.1\",\"Gateway\":\"\"},
{\"IP\":\"::1\",\"Gateway\":\"\"}],\"Mac\":\"00:00:00:00:00:00\",\
"Sandbox\":\"/var/run/netns/cni-7da72ea9-dc89-2072-c22f-69512b36a025\"}},
\"DNS\":[{},{}],\"Routes\":null}"
```

**Comment by anguslees** [comment]
CNI spec says:

> `CNI_IFNAME`: Interface name to set up; if the plugin is unable to use this interface name it must return an error

We have to use the name given in ADD, and we don't get to make up arbitrary vanity interface names.

**Comment by jayanthvn** [comment]
Hi @mikebrow 

Just wanted to follow up on this issue. Kindly let me know if you need any logs from my side.

Thank you.

**Comment by mikebrow** [comment]
Thx for reminding me.. Fell off my stack of todo's.  Yes, we could (1) allow one to change the default from "eth0" to some other default via a containerd(CRI-O plugin config field where if null would revert to eth0). On the other hand others may prefer to (2) use the first in the set as the default (perhaps with a UseFirstNetworkDeviceInterface bool that overrides current behavior (default false)).. However, the order is not present in the CNI result returned from Setup.. (they used a map). So to do option 2 we'll need to change our go-cni interface. 

Any preference, for 1 vs 2? 

There exists documentation in and around Kubernetes for how about pods communicate with each other over eth0. There may be some pushback / upstream issues (testing, docs, ...) with either change.

**Comment by jayanthvn** [comment]
Hi @mikebrow 

Sorry got bit busy with few projects. Before going ahead with the change, I will try the change suggested by @anguslees i.e, to pass the `sandbox` along with `eth0` in the interface list and verify if bandwidth plugin is working as expected. Thanks for helping out on this. 

Thanks Gus for the suggestion :)

**Comment by mikebrow** [comment]
> Hi @mikebrow
> 
> Sorry got bit busy with few projects. Before going ahead with the change, I will try the change suggested by @anguslees i.e, to pass the `sandbox` along with `eth0` in the interface list and verify if bandwidth plugin is working as expected. Thanks for helping out on this.
> 
> Thanks Gus for the suggestion :)

FYI we added the ability to get the raw result  here: https://github.com/containerd/go-cni/pull/68/files#diff-b67a0c563bd29e3d46d4cba43d67e8405b2d4a75f59b45d2a5eacaee606c6d44R50

**Comment by jayanthvn** [comment]
Thank you, will update you soon.

**Comment by jayanthvn** [comment]
Hi @mikebrow 

Sorry for the delay. I tried the fix suggested by @anguslees and it works fine by sending both the eth0 with sandbox and hostveth without sandbox. So will close this issue for now and reach out if anything else is needed. Thank you :)
