### ISSUE TITLE
Support for ephemeral containers .. NamespaceMode=Target 

### ISSUE THREAD

**Issue by phanhuy1502** [containerd/cri#1554]
CRI-API interface has added a namespace mode=Target where we can specify the container to share namespaces (PID, IPC) with another container in the same pod. Is there plan to support this NamespaceMode?
Ref: https://github.com/kubernetes/cri-api/commit/758f2d9705802acd1678630cac0abcba51e869a4

**Comment by mikebrow** [comment]
Not planned yet... let's see if this makes sense for containerd v1.5.

Related links.
KEP: https://git.k8s.io/enhancements/keps/sig-node/20190212-ephemeral-containers.md
Follow up KEP for finishing out ephemeral support: https://github.com/kubernetes/enhancements/pull/1690
PR for kublet/dockershim changes and related CRI changes: https://github.com/kubernetes/kubernetes/pull/84731

**Comment by DawnGuoDev** [comment]
@phanhuy1502  Containerd has been support this. See: [Support PID NamespaceMode_TARGET](https://github.com/containerd/containerd/pull/5203)
