### ISSUE TITLE
Some nodes on GKE giving archive/tar: invalid tar header: unknown

### ISSUE THREAD

**Issue by kahootali** [containerd/cri#1565]
I have a GKE v1.16.12-gke.3 cluster running containerd `containerd github.com/containerd/containerd 1.2.8 a4bc1d432a2c33aa2eed37f338dceabb93641310`
I have 2 services and I am building images through buildah and pushing them to dockerhub on same repository with different tags as I have 1 private repo only. 
Initially one node was failing and the other nodes were working fine and were able to pull & run images, now 2 nodes have started failing and giving error 

```
failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:69ecf019f649c936cf7169e8ef78fd32917891069ee8af974455712e0e1e39d1: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount487017711: archive/tar: invalid tar header: unknown
```
Still 1 node is fine and is able to run images,so for now I have added nodeSelector, but how can I fix other nodes?

**Comment by kahootali** [comment]
I have also ssh'd into nodes, and deleted all existing images of my services, also restarted containerd on nodes, but still no use

**Comment by kahootali** [comment]
@Random-Liu any idea on this?

**Comment by ivantorrellas** [comment]
I just had the same issue in Google cloud GKE, with the `Container-Optimized OS with Containerd (cos_containerd)` image type, with version 1.17.13-gke.2600, had to change back to `Container-Optimized OS (cos)`

**Comment by GerkinDev** [comment]
Hi there,

I've fixed this by adding `--format docker` to my `buildah build-using-dockerfile` command.

See https://bugzilla.redhat.com/show_bug.cgi?id=1826559#c1

**Comment by AkihiroSuda** [comment]
Seems an issue of buildah, so I’m closing this, but feel free to reopen in https://github.com/containerd/containerd if there is still something to be done on containerd side.
