### ISSUE TITLE
Trying to redirect to a different path on a alternative registry

### ISSUE THREAD

**Issue by IBMRob** [containerd/cri#1615]
I am trying to update containerd on Azure Kube so that it will redirect a set of registry requests i.e. 

When it attempts to pull "docker.io/myRepo/MyImage" I would like it to pull from "my.custom.registry/dir/MyImage"

I have been looking at https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-endpoint but not sure its its possible to do the redirection that we are looking to do. 

I have been attempting various combinations such as editing the `/etc/containerd/config.toml` file with
```
[plugins."io.containerd.grpc.v1.cri"]
  ......
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io/myRepo"]
      endpoint = ["https://my.custom.registry/dir/"]
```

with no success

To do the same redirect on OCP we are making the following registries.conf change
```
[[registry]]
  prefix = ""
  location = "docker.io/myRepo"
  mirror-by-digest-only = true
  [[registry.mirror]]
  location = "my.custom.registry/dir"
```

Is what we are trying to do possible?

**Comment by mikebrow** [comment]
> Is what we are trying to do possible?

Not with the code as written. Unfortunately, the decision was made a long time ago that the docker registry would not support namespacing, though the image names make it look like it's namespaced it's not really.  

in the following pull request: `docker pull myregistrydomain:port/foo/bar`

The host and port are `myregistrydomain:port` the image name is `foo/bar`, not bar within the sub-domain foo.

The config you are using is for mirroring host(and optionally port) to a list of host(and port) options for any image.

We'd need more code to figure out you wanted us to use implied name-spacing.

Cheers, Mike

**Comment by IBMRob** [comment]
Thanks @mikebrow 

Interesting a college claimed to have got this working on IKS with a configuration such as
```
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"] <--- 
          endpoint = ["https://my.custom.registry/dir"] <--- 
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."cp.icr.io"] <--- 
          endpoint = ["https://my.custom.registry/dir"] <--- 
```

I tried something similar on my Azure system but its not working. I was expecting the feedback from ``crictl pull` saying that it could not find anything in the mirror either as I know we see this when redirecting using registries.conf but it just reports it can't find it on docker.io, no errors saying not found on `my.custom.registry` either

**Comment by mikebrow** [comment]
yeah we try each of your specified endpoints first then the default endpoint which is docker.io.. We should probably be reporting all of the failures as a list to remove doubt (maybe keep this issue open to track that).  If you like, turn on -l debug when you run containerd.. and you should see evidence of your custom registry failing first when the config is right. 

Note: the college used "docker.io" in the map selector not "docker.io/myRepo"

**Comment by IBMRob** [comment]
> Note: the college used "docker.io" in the map selector not "docker.io/myRepo"

Yeah I can't see how it actually ever worked as it would redirect to a repo that does not exist on the mirror.  I will have a play and see if I can get it working on IKS instead.

**Comment by IBMRob** [comment]
@mikebrow - To work around the different namespaces we are now mirroring the remote folders in our mirrors so hopefully its now just simple redirection we are configuring. 

We updated our configuration with 
```
plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.headers]
      X-Meta-Source-Client = ["azure/aks"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://ourregistry.com"] 
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."cp.icr.io"] 
        endpoint = ["https://ourregistry.com"] 
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."ourregistry.com".auth]
        auth = "xxxxx"
```
but upon doing this it appears its no longer falling back to docker.io due to permissions. When trying to deploy an image using alpine we get 
```
Failed to pull image "docker.io/library/alpine": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/alpine:latest": failed to resolve reference "docker.io/library/alpine:latest": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
```
We know the auth is OK as its pulled from a secret in a cluster where its working. We did try adding 
```
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry-1.docker.io"]
``` 
to the list as well but now the pods are just sitting in `Pending` :(

**Comment by IBMRob** [comment]
I think I have fixed it with 
````
[plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.headers]
      X-Meta-Source-Client = ["azure/aks"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry-1.docker.io,https://ourregistry.com"] 
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."cp.icr.io"] 
        endpoint = ["https://ourregistry.com"] 
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."ourregistry.com".auth]
        auth = "xxxxx"

**Comment by IBMRob** [comment]
Spoke too soon - I get errors such as this when running pods 

`2s          Warning   Failed                    pod/sh                                Failed to pull image "docker.io/operator/mycontainer:1.2.1-20210118-172556-amd64": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/operator/mycontainer:1.2.1-20210118-172556-amd64": failed to resolve reference "docker.io/operator/mycontainer:1.2.1-20210118-172556-amd64": failed to do request: Head https://registry-1.docker.io,https/ourregistry.com/operator/mycontainer/manifests/1.2.1-20210118-172556-amd64?ns=docker.io: dial tcp: lookup registry-1.docker.io,https: no such host`

This looks like its not parsing the entry correctly as its terminating it after the first `/` it finds, its not splitting the domains by `,` as per the docs

**Comment by IBMRob** [comment]
Closing this as this isn't a supported configuration
