### ISSUE TITLE
StopContainer silently ignored when container is in CONTAINER_CREATED state

### ISSUE THREAD

**Issue by irozzo-1A** [containerd/cri#1654]
When a container is [CONTAINER_CREATED](https://github.com/kubernetes/cri-api/blob/897a1c6f320122f3f74e7a5bd9594a863210b016/pkg/apis/runtime/v1alpha2/api.proto#L1014) state a call to StopContainer  has no visible effect:

https://github.com/containerd/cri/blob/f6026296a3991010429db91e7e677f9c9d4861ab/pkg/server/container_stop.go#L55-L63

This seems to respect the [CRI API](https://github.com/kubernetes/cri-api/blob/897a1c6f320122f3f74e7a5bd9594a863210b016/pkg/apis/runtime/v1alpha2/api.proto#L66-L71), that anyway does not seem to cover this specific case. I think this behavior could be misleading for clients, and I had an issue related to this. Would not be easier for the consumers of the API if an error is returned in this circumstance?

>     // StopContainer stops a running container with a grace period (i.e., timeout).
>     // This call is idempotent, and must not return an error if the container has
>     // already been stopped.
>     // The runtime must forcibly kill the container after the grace period is
>     // reached.

**Comment by mikebrow** [comment]
nod.. The behavior of a cri stop request for a container that has not been started .. it is only created, is undefined in cri. But it is defined in the oci runtime spec.  We should probably be allowing it to be created then stopped. https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#lifecycle

But we'll need a test bucket in cri-tools to validate the change is expected and corresponding code in cri-o and kubelet and a comment added for the create/stop sequence in the api/docs.

FYI this repo is archived.  Please open an issue in containerd/containerd.

Cheers, Mike

**Comment by irozzo-1A** [comment]
Closing in favor of: https://github.com/containerd/containerd/issues/6477
