### ISSUE TITLE
Verify Selinux support.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#199]
We've added selinux features in https://github.com/kubernetes-incubator/cri-containerd/pull/157.

However, we don't have test coverage on it. And actually, even in Kubernetes we don't.

We should manually validate it.

/cc @miaoyq

**Comment by miaoyq** [comment]
@Random-Liu OK, I have been working for this.

**Comment by miaoyq** [comment]
I run a sandbox with config file:
```
  "metadata": {
    "name": "security-context-123456",
    "namespace": "default",
    "attempt": 1,
    "uid": "hdishd83djaidwnduwk28bcsb"
  },
  "labels": {
    "neme": "security-context-123456"
  },
  "linux": {
    "namespace_options": {
      "host_pid": false,
      "host_ipc": false
    },
    "security_context": {
      "selinux_options": {
        "user": "system_u",
        "role": "system_r",
        "type": "container_t",
        "level": "s0:c0,c1"
      }
    }
  }
```

but always failed with error print:
```
# crictl runs sandboxconfig1.json 
Run pod sandbox failed: rpc error: code = 2 desc = failed to create task for sandbox "4904efb3028291325ee765f0c56eb77bc2deb9f7ebe4406dcbfeeccfde2bbb8b": runtime create failed: OCI runtime create failed: container_linux.go:265: starting container process caused "process_linux.go:348: container init caused \"write /proc/self/task/1/attr/exec: invalid argument\"": unknown
```
Maybe we should add selinux policy for cri-containerd/containerd like container-selinux for docker.
I think I still do not have enough knowledge about selinux for verifying this.
Could you give some advice for this?

**Comment by Random-Liu** [comment]
@miaoyq I'm not familiar with selinux, either. First of all, have you rebuild your runc with selinux enabled?

**Comment by miaoyq** [comment]
@Random-Liu  Yes, I had rebuilt it with selinux enabled, I think the problem is that we have no set the selinux policy.

**Comment by cpuguy83** [comment]
I guess the main thing would be making sure the type label on the cri-containerd bin is set.

**Comment by cpuguy83** [comment]
Unfortunately the process label does not appear to be set correctly:

```
system_u:system_r:container_runtime_t:s0 root 1471 0.1  4.5 293600 22988 ?     Ssl  21:32   0:00 /usr/local/bin/containerd
system_u:system_r:container_runtime_t:s0 root 1805 0.0  0.5 8912 2708 ?        Sl   21:37   0:00  \_ containerd-shim -namespace k8s.io -workdir /var/lib/containerd
system_u:system_r:container_runtime_t:s0 root 1815 0.0  0.0 1016    4 ?        Ss   21:37   0:00      \_ /pause
```

**Comment by cpuguy83** [comment]
Note that it's just inheriting from containerd-shim (which is set with container_runtime_t)

**Comment by cpuguy83** [comment]
Ok, so `initSelinuxOpts` is returning empty strings if only part of the selinux context is set... should this error out instead? Took a bit of digging to find that this was happening.

Also finding that the `container_t` type is what's causing the `invalid argument` error... if you change to `svirt_lxc_net_t` at least the kernel accepts it... but then there are more errors when runc tries to start the process because evidently the mqueue mount label is not being set.

**Comment by cpuguy83** [comment]
Actually here's the real failure:
```
op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:container_runtime_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c647,c709
```

Removing the code that effectively disables selinux when a custom selinux context is not passed in and then subsequently passing in no selinux context (such that it uses the defaults from the selinux package) you end up with the same error.

**Comment by cpuguy83** [comment]
Implementing the solution in https://stackoverflow.com/questions/44127247/does-anyone-know-a-workaround-for-no-new-privileges-blocking-selinux-transitions at least allows that transition.
`spc_t` is still not allowed in this case.

So it looks like the issue is that the default spec is setting `NoNewPrivileges` to true.
Here's the generated process spec:

```json
{
  "user": {
    "uid": 0,
    "gid": 0
  },
  "args": [
    "/pause"
  ],
  "env": [
    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  ],
  "cwd": "/",
  "capabilities": {
    "bounding": [
      "CAP_CHOWN",
      "CAP_DAC_OVERRIDE",
      "CAP_FSETID",
      "CAP_FOWNER",
      "CAP_MKNOD",
      "CAP_NET_RAW",
      "CAP_SETGID",
      "CAP_SETUID",
      "CAP_SETFCAP",
      "CAP_SETPCAP",
      "CAP_NET_BIND_SERVICE",
      "CAP_SYS_CHROOT",
      "CAP_KILL",
      "CAP_AUDIT_WRITE"
    ],
    "effective": [
      "CAP_CHOWN",
      "CAP_DAC_OVERRIDE",
      "CAP_FSETID",
      "CAP_FOWNER",
      "CAP_MKNOD",
      "CAP_NET_RAW",
      "CAP_SETGID",
      "CAP_SETUID",
      "CAP_SETFCAP",
      "CAP_SETPCAP",
      "CAP_NET_BIND_SERVICE",
      "CAP_SYS_CHROOT",
      "CAP_KILL",
      "CAP_AUDIT_WRITE"
    ],
    "inheritable": [
      "CAP_CHOWN",
      "CAP_DAC_OVERRIDE",
      "CAP_FSETID",
      "CAP_FOWNER",
      "CAP_MKNOD",
      "CAP_NET_RAW",
      "CAP_SETGID",
      "CAP_SETUID",
      "CAP_SETFCAP",
      "CAP_SETPCAP",
      "CAP_NET_BIND_SERVICE",
      "CAP_SYS_CHROOT",
      "CAP_KILL",
      "CAP_AUDIT_WRITE"
    ],
    "permitted": [
      "CAP_CHOWN",
      "CAP_DAC_OVERRIDE",
      "CAP_FSETID",
      "CAP_FOWNER",
      "CAP_MKNOD",
      "CAP_NET_RAW",
      "CAP_SETGID",
      "CAP_SETUID",
      "CAP_SETFCAP",
      "CAP_SETPCAP",
      "CAP_NET_BIND_SERVICE",
      "CAP_SYS_CHROOT",
      "CAP_KILL",
      "CAP_AUDIT_WRITE"
    ]
  },
  "noNewPrivileges": true,
  "oomScoreAdj": -998,
  "selinuxLabel": "system_u:system_r:svirt_lxc_net_t:s0:c0,c1"
}
```

**Comment by cpuguy83** [comment]
container-selinux needs to be updated to support no new privs.

**Comment by cpuguy83** [comment]
I can't seem to force the sandbox to not set no new privs for some reason.

**Comment by crosbymichael** [comment]
This can be closed for now as well have selinux supported.
