### ISSUE TITLE
Binary portability

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#213]
In https://github.com/kubernetes-incubator/cri-containerd/pull/210, we build release tarball which includes all binaries required for cri-containerd to run.

However, it's not clear to me how portable is golang binary across different OS distributions. Currently, most binaries are still dynamically linked, can they run on different OS distributions?

We may need to figure it out, or think of a better solution for distribution.

/cc @kubernetes-incubator/maintainers-cri-containerd 
Also cc @crosbymichael @stevvooe  who may have more experiences or opinions on this.

**Comment by crosbymichael** [comment]
As long as they are dynamic then you should be good for different OSes.  This will cover the major requirements for linux amd64.

The hard part is with different arch.  Go is only so good at cross compiling so far but will start to fall short.

Overall, we usually depend on packagers/distros to handle this and provide source releases for everything else.  I'm not sure I have any good advice here but this is what we plan on doing with containerd.
