### ISSUE TITLE
Ambient Capabilities

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#216]
This is supported since Linux 4.3.

This is added in runtime-tools https://github.com/opencontainers/runtime-tools/blob/master/generate/generate.go#L1024.

This is not used in docker and containerd. https://github.com/containerd/containerd/blob/73ac66eecfb3e2c8635cab04d94adadbd55b1830/spec_unix.go#L85

Should we set it?

**Comment by crosbymichael** [comment]
No, there is more work to be done with ambient caps in order to enable it in a secure way.

ref: https://github.com/moby/moby/issues/27590

**Comment by Random-Liu** [comment]
Close this in favor of https://github.com/kubernetes/community/pull/2285.
