### ISSUE TITLE
The PR "put containerd-shim into pod cgroup" was reverted.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#217]
We should debug it and add the PR back.

**Comment by Random-Liu** [comment]
Move this to next release. This is not supper urgent, because Kubelet is not using pod level cgroup stats anyway.

**Comment by Random-Liu** [comment]
@miaoyq @yanxuean Don't know whether you guys are interested in this.

We want to put containerd-shim into pod cgroup. And PR https://github.com/kubernetes-incubator/cri-containerd/pull/193 did make it.

However, after https://github.com/kubernetes-incubator/cri-containerd/pull/193 is merged, we saw that containerd frequently reports error saying that the specified pod cgroup is not created.

We need to:
1) Fetch the commit back;
2) Run node e2e test to debug this, the bug may either be in cri-containerd or kubelet.
3) Fix the bug.

If you guys are not interested, I could do this later on. :)

**Comment by miaoyq** [comment]
@Random-Liu I will try to debug and fix this.

**Comment by Random-Liu** [comment]
Moved to beta milestone.

**Comment by Random-Liu** [comment]
One test failure:
* containerd.log: https://storage.googleapis.com/lantaol-g8r-logs/containerd.log
* cri-containerd.log: https://storage.googleapis.com/lantaol-g8r-logs/cri-containerd.log
* kubelet.log: https://storage.googleapis.com/lantaol-g8r-logs/kubelet.log

**Comment by Random-Liu** [comment]
Move this to next release. @abhi is looking into this.

**Comment by Random-Liu** [comment]
Remove this from the milestone. It is not top priority now.
