### ISSUE TITLE
Add support for runc hook specs

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#405]
The issue is the OCI runtime spec has support for specifying hooks that are called during the container lifecycle events. runc has implemented these hooks.  CRI does not currently provide a way to specify these hooks for inclusion into the container config.json.  We should consider adding support for hook config to cri-containerd. 

See cri-o support for specifying runc hooks here:
https://github.com/kubernetes-incubator/cri-o/blob/master/hooks.md

Hooks explained here: https://github.com/opencontainers/runtime-spec/blob/master/config.md#prestart

The alternative for runc hook users is to proxy or replace runc with their own version of runc, which is not a good solution.

**Comment by Random-Liu** [comment]
@mikebrow In Kubernetes, we do have `PostStart` and `PreStop` hook, but we are using exec to implement it.

Runc may help us implement more hooks, e.g. `PreStart` and `PostStop`.

**Comment by alban** [comment]
https://github.com/containerd/cri/pull/1498 was merged and it helps somewhat with OCI hooks but it does not help for my use case (https://github.com/containerd/cri/issues/1488#issuecomment-631601626). The workflow is impractical for automation from a DaemonSet running in Kubernetes pods. It would need to:
1. Talk to kube-apiserver to get the list of [Runtime Classes](https://kubernetes.io/docs/concepts/containers/runtime-class/).
2. Find out the containerd configuration file. It's usually in /etc/containerd/config.toml but containerd could be executed with a different path for configuration (with the `-c` flag). Also, there could be different `containerd` processes running on the node; to find out which one is used by the Kubelet process, we would have to inspect the kubelet command line and find out who is listening at the other end of the `--container-runtime-endpoint=` socket.
3. Identify which `base_runtime_spec` to patch in the configuration file. As far as I understand, there might be several if there are several runtime classes found in step 1.
4. If the `base_runtime_spec` option already points to a file, it needs to be patched. To remove the OCI hook, it needs to be patched back. If several tools patch the same file for their respective OCI hooks, there is a risk to step over each other toes.
5. Restart containerd so the config change is taken into account. I am not sure if there is a gRPC API for that. That would break existing connections (kubectl-exec, kubectl-attach, etc.).


So I think we still need a way for dynamically configuring OCI hooks by dropping a file in a directory like cri-o.

**Comment by mikebrow** [comment]
We haven't forgotten about this issue.  https://github.com/containerd/cri/issues/1488#issuecomment-631630370

Plan is to add support for these hooks (the crio way) when the oci spec hooks are supported by runc. The oci spec hook changes are merged. @RenaudWasTaken 's runc pr to support the hooks https://github.com/opencontainers/runc/pull/2229 is taking longer than expected to merge.

There is a related workgroup forming that you may be interested in: https://lists.cncf.io/g/cncf-sig-runtime/topic/new_workgroup_container/74636697?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,74636697

**Comment by RenaudWasTaken** [comment]
> opencontainers/runc#2229 is taking longer than expected to merge

I'm not too worried about this, it will get merged eventually!

> There is a related workgroup forming that you may be interested in:

The Container Device (COD) Working Group might be able to help, I had an example of the specification (Container Device Interface) we had [come up with here](https://github.com/RenaudWasTaken/cdi).

It might be able to help in your case @alban but it seems like you really want something similar to podman hooks right?
In any case we'd be happy to hear input from different people, feel free to [participate on this issue](https://github.com/cncf/sig-runtime/issues/24) and join the meetings!

**Comment by mikebrow** [comment]
> > [opencontainers/runc#2229](https://github.com/opencontainers/runc/pull/2229) is taking longer than expected to merge
> 
> I'm not too worried about this, it will get merged eventually!
> 
> > There is a related workgroup forming that you may be interested in:
> 
> The Container Device (COD) Working Group might be able to help, I had an example of the specification (Container Device Interface) we had [come up with here](https://github.com/RenaudWasTaken/cdi).
> 
> It might be able to help in your case @alban but it seems like you really want something similar to podman hooks right?
> In any case we'd be happy to hear input from different people, feel free to [participate on this issue](https://github.com/cncf/sig-runtime/issues/24) and join the meetings!

Yes podman hooks.. After reviewing them I don't see a reason to do it another way. Their design seems clean, would be nice to have one schema / model for hook injection/filtering.

**Comment by moolen** [comment]
hej @mikebrow just FYI: there's another use-case for oci-hooks (i referenced the issue above). I think it would be important to have the `when` semantics from the [podman hook spec 1.0.0](https://github.com/containers/podman/blob/54a9ecc2629093ca58050a8f7418908bc209cec5/pkg/hooks/1.0.0/hook.go#L17-L23) to filter out pods which really need the hooks.

I think using global hooks is O.K. but may - at least for the seccomp use-case - not be the ideal solution. I'm wondering if pushing the hook configuration up the stack (e.g. Pod spec) is a good idea. Did you investigate further into that direction (are there KEPs or issues in that direction?)

I consider picking this one up if you don't intend to further work on your PR (tho with a different perspective).

**Comment by mikebrow** [comment]
We are working this through the new NRI (see new containerd/nri repo + PRs that have been merged in /cri) and discussing new keps at the k8s level with sig-node, and there is a CNCF COD CDI workgroup, and we are working on merging that with the NRI effort. If we can support all the system level hooks with NRI plugins that may be the better route in the long run vs supporting both simultaneously.  I still think "it would be nice to have one schema / model for hook injection/filtering." And that model may be NRI. If NRI ends up not covering the gamut of needed scenarios we could probably go with two (NRI + libpod hooks injection/filtering).

**Comment by erkules** [comment]
Any updates on this? The Security Profiles Operator uses hooks also i.e.

**Comment by dmcgowan** [comment]
This repo is being archived, I'll let Mike decide whether to keep closed or transfer

**Comment by mikebrow** [comment]
Nod.. let's keep this open till one or the other is production ready in containerd, or both are integrated if neither supports the known use cases.
