### ISSUE TITLE
Handle containerd event reliably

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#434]
Forked from https://github.com/kubernetes-incubator/cri-containerd/issues/62.

Today, we rely on containerd event to figure out whether a container exits or not.

However, when handling an event, if there is an error, we'll just report error and discard the event, e.g. https://github.com/kubernetes-incubator/cri-containerd/blob/master/pkg/server/events.go#L91-L143.

Once that happens, the container will stay in running forever, although it already exists. We should:
1) Either to periodically relist to consolidate the state;
2) Or requeue the event, and handle it again.

**Comment by Random-Liu** [comment]
@abhi Are you interested in this one?

**Comment by yanxuean** [comment]
I prefer to choose No. 1.

**Comment by yanxuean** [comment]
@Random-Liu 
I don't understand. Must we maintain status for every container in local? 
I think the cost is bit of high.
1. For No.1, to relist:
    The will is duplicate with pleg.relist in kubelet. 
2. for No.2. requeue the event
    What if containerd sent event to us during restart cri-container? 
    And maybe there are some abnormal case in containerd.   
    I think it is difficult to reliably maintain the status.

What do you think we get status from containerd directly when we need status?
Only kubelet will use this. we can keep cri-containerd simple, just as adapter.

**Comment by Random-Liu** [comment]
> What do you think we get status from containerd directly when we need status?
Only kubelet will use this. we can keep cri-containerd simple, just as adapter.

The problem is that containerd doesn't persist container status, e.g. exit code, started/finished timestamp,  OOM etc. After task is deleted, containerd-shim is stopped, all these are gone.

**Comment by yanxuean** [comment]
I will study containerd again late.  Do you decide which proposal we will use?

**Comment by Random-Liu** [comment]
Move this to next release, this need further discussion.
I think proposal 2 is more align with current design, and should be simpler.
If we find out that it's insufficient, we could change to relist model later. I think we should give proposal 2 a shot first. :)

**Comment by Random-Liu** [comment]
@yanxuean @miaoyq We also need to do this. Given that `list` is expensive, I prefer we choose proposal 2.

**Comment by yanxuean** [comment]
As the cri-container has been a plugin of containerd,  The rely on containerd event is reliable.

**Comment by yanxuean** [comment]
The proposal 2 is good.

**Comment by Random-Liu** [comment]
> The proposal 2 is good.

Agree.

@yanxuean Thanks! I'll assign this to you 2. :P

**Comment by wangpung12** [comment]
ดี
