### ISSUE TITLE
is there any architectural drawings for beginners?

### ISSUE THREAD

**Issue by czm4514** [containerd/cri#446]
As a beginer, I want to know more about this project so that i can use the cri-containerd into our kubernetes cluster. 
I want to know if you have an architectural picture like [containerd](https://github.com/containerd/containerd) if yes. Can not be shared? if not,
Is it possible to draw the structure as soon as possible, so that later can learn.

**Comment by czm4514** [comment]
@Random-Liu please give some helps.

**Comment by Random-Liu** [comment]
I usually use this one:
![image](https://user-images.githubusercontent.com/5821883/33410317-831011fe-d534-11e7-86f6-9c5c95913b04.png)
See https://www.slideshare.net/Docker/kubernetes-cri-containerd-integration-by-lantao-liu-google

**Comment by Random-Liu** [comment]
Let's keep this issue open. We should have a document in the repo explaining how cri-containerd works.

**Comment by czm4514** [comment]
thank you very much.

**Comment by nguyenvulong** [comment]
May I ask why in the image you had 2 different containers that named "container A" and "sandbox container"? is "sandbox" just a name or you wanted to imply something?

**Comment by mikebrow** [comment]
Each pod gets one normally hidden container called the sandbox container, or pod sandbox container. The container image for the pod sandbox container is called the pause container. This pod sandbox container is used to host shared resources. If you google around you'll find this pod sandbox container is sometimes just called the pause container.

**Comment by mikebrow** [comment]
Naming is hard. Sometimes we call pods at the CRI level sandboxes .. sometime we call them pods.. so we decided a long time ago to just call them pod sandboxes.  At some point in the future we'll probably have support for more types of sandboxes than just pod sandboxes. Watch this space..  And when I say this.. I mean containerd/containerd project because this containerd/cri project is archived.  Cheers, Mike

**Comment by nguyenvulong** [comment]
Mike, thank you so much for the clarification.
I did some reading in ianlewis’ blog and i found it fascinating. Starting off late with K8S and skipping a lot of details of how the community and enterprises devised K8S nowadays from Docker (and beyond, LXC for example) made me overlooked this beauty.

A diagram really speaks a thousand words. I’ll come back with some of them when i’m ready.

p/s ah yes, i was aware of the project moved. Cheers!

**Comment by mikebrow** [comment]
yeah we've got lots of follow up diagrams for this see intro and deep dives over the last couple years..

**Comment by mikebrow** [comment]
oh and cri-containerd is now built into containerd as an internal plugin.. so it's not using grpc to talk to containerd services anymore ...
the calls are direct.
