### ISSUE TITLE
Setup PR cluster e2e test.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#461]
Currently we only have PR node e2e test. And cluster e2e test is still flaky now.

However, we may still want a cluster e2e test. It shouldn't run by default, but should be triggerable, so that we could run it on PR if we think a test may break cluster e2e test, such as https://github.com/kubernetes-incubator/cri-containerd/pull/451.

**Comment by mikebrow** [comment]
Two edged sword. Cluster e2e has always been flaky.  But one could argue it's flaky because it needs to be fixed, and to get fixed it needs to be run more often to find, debug, and route out the flakes.

**Comment by Random-Liu** [comment]
Given the following reasons:
1) As @mikebrow said, cluster e2e is not as stable as node e2e.
2) Compared with node e2e, cluster e2e is less relevant to the container runtime.
3) Cluster e2e is resource consuming.
4) We already have per-hour CI cluster e2e.

Given so, I don't think we need PR cluster e2e test. Let's close this one.
