### ISSUE TITLE
Change CRI Status info to be an array instead of a map.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#472]
CRI container runtime could not control fields order with map.
We should use an array of key-value instead.

We should do this in Kubernetes 1.10.

**Comment by mikebrow** [comment]
To late to change it now?

**Comment by Random-Liu** [comment]
Yeah

**Comment by kzys** [comment]
Are we still want to do that?

**Comment by Random-Liu** [comment]
@kzys I think we are satisfied with #475 for now, so probably no need to make this change. :)
