### ISSUE TITLE
 Supports configuring the log level without exiting the program

### ISSUE THREAD

**Issue by miaoyq** [containerd/cri#495]
In a production environment, the log level is usually set to a lower level. However, we also need to see more detailed log information when debugging a issue, but don't want to quit the program in order to protect the current context.

So I think we should support configuring the log level without exiting cri-containerd.

**Comment by Random-Liu** [comment]
@miaoyq How does other system usually support this? Add an API, or use signal, or something?

**Comment by miaoyq** [comment]
@Random-liu Use signal like dumpstack, docker support reload config file via SIGHUB signal that contains log level setting.

**Comment by miaoyq** [comment]
@Random-Liu We should support setting log level at least.

**Comment by mikebrow** [comment]
interesting.. not against dynamic log level.. but it's pretty easy to cycle cri-containerd

**Comment by cpuguy83** [comment]
Agreed, but also cycling can cause you to lose data about a problem you are experiencing.
