### ISSUE TITLE
Cleanup after reorg to containerd

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#529]
- [x] Rename packages from `github.com/kubernetes-incubator/cri-containerd` to `github.com/containerd/cri`. (https://github.com/containerd/cri-containerd/pull/533)
- [x] Cleanup kubernetes-incubator related document, such as README.md, CONTRIBUTING.md, code-of-conduct.md etc. @mikebrow 
- [x] Change existing CI to run against new repository. 
- [x] Add new boilerplate check. @mikebrow (#536)

I'll add more over time.

@containerd/containerd-maintainers

**Comment by mikebrow** [comment]
I really like idea of moving to "cri" but for the "discussion":
1) would we be considering a "cri" package name for any of the code, say the new plugin code
2) what about the cri-containerd socket name?
3) are we concerned about potential conflicts / confusion with the kubelet/apis/cri package

**Comment by crosbymichael** [comment]
I like simple, `cri` is simple ;)

**Comment by Random-Liu** [comment]
@crosbymichael I also prefer the name `cri`. But on second thought, I think we may want to do the rename after we make the plugin model work.

The problem is that if we rename it now:
1) It's hard to explain in the document, such as `README.md`, because the plugin mode is not in place yet. `cri-containerd` daemon is still the only option today, and people heard about.
2) It's not yet time to send out public announcement yet, because we haven't finished the work.

To make people less confuse about this transition, I propose we:
1) Keep the `cri-containerd` name for now, because that's how people understand this and how it is documented and advertised today
2) Finish the plugin mode.
3) Vendor the plugin in containerd.
4) Rename the project to `cri` and update document correspondingly at that time.
5) Broadly announcement that:
  a) `containerd` (and potentially `docker`) natively support CRI now. Just go to use `containerd` and `docker` directly. Users don't need to understand a new concept `cri-containerd` any more, the repo is renamed to `containerd/cri`. (I think this is a clear enough announcement, and people should have understood the concept `containerd` and `docker` already. They'd like to understand one less concept.)
  b) For user likes `cri-containerd`, here is how you continue using it...But please note that...

**Comment by crosbymichael** [comment]
Sounds like a good plan to me.

**Comment by Random-Liu** [comment]
We've done most of this. The cri-containerd to cri renaming will be tracked in https://github.com/containerd/cri/issues/660.

Close this one.
