### ISSUE TITLE
Evaluate the need to disable IPv6 DAD in cri-containerd

### ISSUE THREAD

**Issue by abhi** [containerd/cri#566]
containerd/cri-containerd#563 provides a knob to enable DAD on pod network interfaces and turns off the DAD for the pod by default. This is done to speed up the pod creation. If DAD is enabled , the interface binding is delayed until NS messages guaranteed no duplicate IPv6 addresses in the cluster. As explained here https://github.com/containerd/cri-containerd/pull/563#issuecomment-359618326,  we need to evaluate If the runtime needs to control this knob or should the CNI plugin take care of this.

**Comment by abhi** [comment]
The release notes of cni plugin version 0.7.0-rc2 says that DAD can be can be disabled. 
https://github.com/containernetworking/plugins/releases
Once we update it we can remove the explicit dad disable in cri-containerd and bench mark it .

**Comment by Random-Liu** [comment]
The latency issue is fixed by https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2Fcontainernetworking%2Fplugins%2Fcommit%2F97664d8a6af0d70303b5015b22e472a853423764.
