### ISSUE TITLE
Add `ctr cri` and retire `ctrcri`

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#590]
We added `ctrcri` binary in https://github.com/containerd/cri-containerd/pull/586 as a supplement of `crictl` for cri-containerd. Especially for loading image.

After cri-containerd is vendored into containerd, we may want to merge this command into `ctr` as well. A subcommand in `ctr` seems a good option.

**Comment by stevvooe** [comment]
@Random-Liu Does this need higher stability guarantees than we have for the CLI at this time?

**Comment by Random-Liu** [comment]
@stevvooe No.

* We only need a `load` command today, and I don't expect it to be changed anytime soon.
* Even if it is changed, this is only used in Kubernetes bootstrapping on GCE, and configured through an [ENV](https://github.com/containerd/cri-containerd/blob/master/cluster/gce/env#L16). People can easily change the ENV based on the containerd version they are using.

**Comment by Random-Liu** [comment]
I'll continue this work after https://github.com/containerd/containerd/issues/2210 is fixed.

It may makes our test flaky if we upgrade containerd now.
