### ISSUE TITLE
Signed container image support

### ISSUE THREAD

**Issue by harche** [containerd/cri#624]
Hi,

Does cri-containerd support signed container image schemes (like docker content trust, or [Simple GPG based signing](https://rhelblog.redhat.com/2016/07/22/container-image-signing/)? 

This is very critical for the security sensitive environments. 

If this is not there yet, I can rename this issue to RFC and we can discuss how can we implement it in cri-containerd.

**Comment by Random-Liu** [comment]
> Does cri-containerd support signed container image schemes (like docker content trust, or Simple GPG based signing?

@harche We don't support it yet.

The problem is that for Kubernetes, it is still not clear whether we should handle this at the cluster admission phase; kubelet admission phase or container runtime.

**Comment by Random-Liu** [comment]
@harche But I do think it is good to have this support in cri-containerd.

**Comment by 3r1co** [comment]
Hello, could you please let me know if there is any update on that subject? We are currently evaluating how to integrate container integrity in our CI/CD Pipelines and are wondering about different Container Runtime Compatibilities.

**Comment by trishankatdatadog** [comment]
@3r1co The problem is that there is no OCI standard for TUF

Right now, there is Docker Content Trust (which uses Notary, an implementation of TUF), but it's Docker-specific

Maybe someone can help us write an OCI standard for TUF?

Cc @justincormack @JustinCappos

**Comment by justincormack** [comment]
"Docker Content Trust" is not Docker specific. But the metadata in Notary is not stored in OCI annotations; I am planning to work on an OCI spec for TUF metadata soon.

**Comment by trishankatdatadog** [comment]
Thanks for the clarification, @justincormack! Would love to collaborate on the OCI spec for TUF metadata 👍

**Comment by perezjasonr** [comment]
any update on this? is it still being pursued? this would be amazing.

**Comment by thaJeztah** [comment]
- https://www.docker.com/blog/community-collaboration-on-notary-v2/
- https://github.com/notaryproject/
- https://github.com/notaryproject/nv2
