### ISSUE TITLE
Use containerd event exchange

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#627]
For plugin mode, we should use containerd event exchange https://github.com/containerd/containerd/blob/129167132c5e0dbd1b031badae201a432d1bd681/plugin/context.go#L36 to get rid of one extra layer of grpc, which makes the event handling more reliable.

**Comment by Random-Liu** [comment]
Ref https://github.com/containerd/containerd/issues/2120

**Comment by crosbymichael** [comment]
+1  All of the grpcs should be switched over to internal APIs before we can do a 1.1 release with CRI

**Comment by Random-Liu** [comment]
> +1 All of the grpcs should be switched over to internal APIs before we can do a 1.1 release with CRI

@crosbymichael We'd like to have a release for Kubernetes 1.10 (March 21st).
If we can cut a containerd 1.1-x release around that time, we can deprecate standalone cri-containerd now.
If we can't, we may have to keep the standalone mode and cut a release for the standalone mode around that time.

Can we finish the grpc change before that? Or we may need to cut 1.1-x release later?
Maybe we should keep the standalone mode and cut a release for Kubernetes 1.10?

**Comment by crosbymichael** [comment]
We are not considering the integration complete until it does not use GRPC

**Comment by Random-Liu** [comment]
I will try to get rid of the extra grpc layer recently, and will handle this issue together with that.

**Comment by Random-Liu** [comment]
Ref https://github.com/containerd/containerd/issues/2183

**Comment by Random-Liu** [comment]
This is done in https://github.com/containerd/cri/pull/658.
Close.
