### ISSUE TITLE
cri-containerd load image failed

### ISSUE THREAD

**Issue by hmtai** [containerd/cri#638]
When I load an image with the command bellow:
```
cri-containerd load pause.tar
```
an error occurd:
```
Error: failed to load image: rpc error: code = Unknown desc = failed to import image: create docker manifest: layer "3a260e652b2585d5feaaf04ae480827caeba0adbc77fb84cfc6427302063cb05/layer.tar" not found
```
It works well with Docker.

The circtl vision:
```
Version:  0.1.0
RuntimeName:  cri-containerd
RuntimeVersion:  1.0.0-beta.1
RuntimeApiVersion:  0.0.0
```

**Comment by Random-Liu** [comment]
@hmtai How do you create the `pause.tar`.

I tried with `k8s.gcr.io/pause-amd64:3.1`, and it works for me:
```console
$ sudo ctrcri --address=/run/containerd/containerd.sock load pause.tar 
Loaded image: k8s.gcr.io/pause-amd64:3.1
```

**Comment by mikebrow** [comment]
Works here...
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri-containerd$ sudo docker pull k8s.gcr.io/pause-amd64:3.1
3.1: Pulling from pause-amd64
67ddbfb20a22: Pull complete 
Digest: sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610
Status: Downloaded newer image for k8s.gcr.io/pause-amd64:3.1
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri-containerd$ sudo docker save k8s.gcr.io/pause-amd64:3.1 > pause.tar
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri-containerd$ ls pause.tar
pause.tar
mike@mike-VirtualBox:~/go/src/github.com/containerd/cri-containerd$ sudo ctrcri load pause.tar 
Loaded image: k8s.gcr.io/pause-amd64:3.1
```

**Comment by hmtai** [comment]
@Random-Liu I use docker save .I can not find the command ctrcri.How to use ctrcri?
```
docker save  k8s.gcr.io/pause-amd64:3.0 -o my-pause.tar
```

**Comment by hmtai** [comment]
@Random-Liu @mikebrow cri-containerd load can not load the image which has link image layer?

**Comment by Random-Liu** [comment]
@hmtai What do you mean by "link image layer?

**Comment by Random-Liu** [comment]
@hmtai Yeah, symlink file is skipped https://github.com/containerd/cri-containerd/blob/master/pkg/containerd/importer/importer.go#L104.

I think it is for security consideration. @AkihiroSuda 

Why `648a008b041c2bed7d854226dfa4a40476222c9b081a879e74b0b6bcc7578e13/layer.tar` is a symlink to `../768d4f50f65f00831244703e57f64134771289e3de919a576441c9140e037ea2/layer.tar`...

**Comment by qiujian16** [comment]
docker save will create symlink for some layers https://github.com/moby/moby/blob/master/image/tarexport/save.go#L378-L385, we may not skip the symlink file?

**Comment by Random-Liu** [comment]
We should fix this.
