### ISSUE TITLE
develop section in readme should be updated

### ISSUE THREAD

**Issue by qiujian16** [containerd/cri#652]
I try to run make & make install and only get the containerd/ctrcri binary. It seems cri-containerd is merged into containerd? Also the socket that kubernetes connects to cri-containerd is changed to /run/containerd/containerd.sock? If these are correct, we should update the readme of the project.

**Comment by Random-Liu** [comment]
@qiujian16 Thanks for trying this out!

We are planning to cut a release this month, and all documents will be updated. :)

**Comment by Random-Liu** [comment]
This has been updated. :)
