### ISSUE TITLE
Rename `cri-containerd` to `cri`

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#660]
`cri-containerd` is now purely a plugin of containerd, even the standalone mode does not exist anymore. (see https://github.com/containerd/cri-containerd/issues/642).

It makes sense to rename the repo from `cri-containerd` to `cri` now. We need to:
- [x] Update all imports and repo name.
- [x] Update test infrastructure. https://github.com/kubernetes/test-infra/pull/7246
- [x] Update variable names and comments. (https://github.com/containerd/cri/pull/683)
- [x] Update all documents.

@mikebrow Will drive this. And any help is welcomed! :)

**Comment by mikebrow** [comment]
TODO: The config is changed. We need to generate a new output used in crictl.md .

**Comment by mikebrow** [comment]
The README.md still needs rework, "Explain the transition from cri-containerd to containerd, The dependency/build section doesn't make much sense as well..."
