### ISSUE TITLE
Generate document for CRI config.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#664]
I hope we can auto generate a toml document for CRI config.

If there is no easy way to auto generate, at least we can manually do that.

**Comment by Random-Liu** [comment]
Don't think we have time to finish this one. Let's write a document for now. We should do https://github.com/containerd/containerd/pull/2215 in next release.

**Comment by Random-Liu** [comment]
We plan to cut an early `rc.1` release today to carry several fix and improvement.

We need further discussion about this approach in https://github.com/containerd/containerd/pull/2215, so remove this from the milestone for now.

We need a comprehensive document for configurations anyway.

**Comment by Random-Liu** [comment]
I think we can close this now. We decided to manually manage the doc config.

**Comment by miaoyq** [comment]
OK
