### ISSUE TITLE
Prevent mounting under module directory

### ISSUE THREAD

**Issue by dmcgowan** [containerd/cri#686]
After running the critest I noticed a mount in the module directory

```
shm on /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/aa3f30975daf5225994ef38d618678899ded0e3c1b313206825195d2ecf17cf2/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```

Mounts should be done under `/run/containerd` if they are tied to a pod/container or in `/var/lib/containerd/tmpmounts` if they are used directly by the containerd process

**Comment by Random-Liu** [comment]
This requires fs layout change, let's do it before the release.
