### ISSUE TITLE
Better support Katacontainers stop

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#687]
Forked from https://github.com/containerd/containerd/issues/2217.

> @sboeuf After thinking about this more, I think this should be handled in cri-containerd. TaskExit event from containerd simply means the init process exits, it doesn't necessarily implies that the container state is changed.

> As for cri-containerd, actually we've already supported your use case today. Let's say we use StopContainer to stop a container:

> StopContainer stops the container, and wait for internal container state to transit to "stopped".
events.go receives the TaskExit event, and try to Delete the task.
Delete checks whether the task is in stopped state but returns error, because container state is still running for kata containers.
events.go requeues the event, and will deal with the event again with an exponential backoff. The backoff increases from 1s to 5 min.
When events.go handles the event the Xth time, it is able to Delete the task and update internal container state, because the state become stopped.
StopContainer see the internal container state change and return.
If we find the backoff log is too spammy we can improve it. But I think the functionality is in place. :)

> @yanxuean The event handling backoff you added is useful! :)

@sboeuf Are you OK with the current support we provide?

**Comment by sboeuf** [comment]
Thanks for describing the current behavior @Random-Liu.
If what you call the "container state" is the result of what you get doing `runc state my_container_id`, then I think the case I was describing is completely covered :)

Could you show me a few links from the code illustrating the sequence you've described (just curious!) ?

**Comment by Random-Liu** [comment]
@sboeuf The logic is mainly in https://github.com/containerd/cri/blob/master/pkg/server/container_stop.go and https://github.com/containerd/cri/blob/master/pkg/server/events.go

**Comment by Random-Liu** [comment]
Let's close this one. :)
