### ISSUE TITLE
RunPodSandbox() fails due to network error.

### ISSUE THREAD

**Issue by kunalkushwaha** [containerd/cri#699]
Sandbox is created successfully but  `RunPodSandBox() ` fails with below error.

I tried separately with [sample code](https://gist.github.com/kunalkushwaha/8d0fffa2ffb80e2120e87abbfef5926f#file-cri-test-go) too, same error occurs. It is reproducible with latest containerd and cri-containerd

```
rpc error: code = 2 desc = failed to get network status for sandbox "fb58bf5ab96b7e1197616d5406eda1a5845b39adfc322f1efbd49d6e36472ef7": Unexpected command output Device "eth0" does not exist.
 with error: exit status 1
```

**Comment by abhi** [comment]
@kunalkushwaha which cni plugin are you using ? Can you post your CNI network config file ?

**Comment by abhi** [comment]
If you do not have the network config in the default location prior to starting the CRI service, you will need to using the Status() to ensure the networkstatus is ready and loaded. 
We moved to https://github.com/containerd/go-cni for the cni library. A Status() check is needed to load the cni config. There is no background watch being done. 
So:
1) If cni config is added prior to starting CRI , it will be loaded.
2) If cni config is added after CRI is started, It will loaded on the next Status() check.

**Comment by Random-Liu** [comment]
@kunalkushwaha Does this resolve your problem?

**Comment by kunalkushwaha** [comment]
@abhi @Random-Liu below are my config files for CNI

```
$ cat /etc/cni/net.d/99-loopback.conf 
{
        "cniVersion":"0.3.1",
        "type":"loopback"
}


~/go/src/github.com/moby/buildkit/examples/buildkit4 on  cni-network-worker! ⌚ 9:25:46
$ cat /etc/cni/net.d/crio-bridge.conf 
{
    "cniVersion": "0.2.0",
    "name": "crio-bridge",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}

```

Also, I am using go-cni for one of my WIP PR https://github.com/moby/buildkit/pull/309 and it works fine with these CNI configuration. 

Will try to debug more on this.

**Comment by Random-Liu** [comment]
I see similar issue in containerd test:
```
E0327 02:43:26.722169    3440 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "ba2e941b7dae2f7dcb17439e673a1a14147757154119c3698b5548191a78914d": failed to set bridge addr: could not add IP address to "cni0": file exists
Mar 27 02:43:26.723: INFO: Unexpected error occurred: rpc error: code = Unknown desc = failed to setup network for sandbox "ba2e941b7dae2f7dcb17439e673a1a14147757154119c3698b5548191a78914d": failed to set bridge addr: could not add IP address to "cni0": file exists
```

**Comment by abhi** [comment]
@kunalkushwaha may be you are running into this ? https://github.com/kubernetes/kubernetes/issues/25281

**Comment by abhi** [comment]
@Random-Liu your issue is different from @kunalkushwaha issue.
This is an error from bridge plugin. Its a netlink error. I will checkout the possibilites for bridge plugin.

**Comment by abhi** [comment]
Thanks ! Closing the issue.
