### ISSUE TITLE
Customize sandbox image

### ISSUE THREAD

**Issue by qiujian16** [containerd/cri#718]
Currently cri-containerd uses a default plugin configuration that uses k8s.gcr.io/pause:3.1 as the sandbox image. However, we would like to use a customized sandbox image.

It would be nice if there is a way that we can override default plugin configuration in some way (maybe we can, but I cannot find the document about it..)

**Comment by qiujian16** [comment]
I think if find a way https://github.ibm.com/IBMPrivateCloud/icp-containerd-binaries/blob/master/cri-containerd/x86_64/1.0/ubuntu16.04/opt/containerd/cluster/gce/cloud-init/master.yaml#L29-L47, will validate and close this.

**Comment by mikebrow** [comment]
output the default config:
containerd config default

default config location:
/etc/containerd/config.toml

change sandbox_image to your liking:
sandbox_image = "k8s.gcr.io/pause:3.1"

**Comment by Random-Liu** [comment]
@qiujian16 Can we close this issue after #719 is merged?

**Comment by qiujian16** [comment]
Yes, sure!

**Comment by Random-Liu** [comment]
@qiujian16 Thanks!
