### ISSUE TITLE
remove sandbox failed

### ISSUE THREAD

**Issue by hmtai** [containerd/cri#732]
When I remove sandbox:
`crictl stopp 5dc62a1a5e19c
FATA[0010] stopping the pod sandbox "5dc62a1a5e19c" failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "5dc62a1a5e19c4c1412cba8134372266a799205d5bf8b38e8deecc4555063528": dial tcp 10.10.25.230:4001: getsockopt: connection refused`

**Comment by hmtai** [comment]
@Random-Liu Yes ,I am using calico.When I unstall the kubernetes environment,I find that I can not remove some sandboxes because the error above.I can not clean up the environment:(

**Comment by Random-Liu** [comment]
@hmtai If I understand correctly, calico cni pod network teardown needs to talk with the calico demonset.

It seems that your either removed calico or apiserver before you stop this pod.

You may want to keep them running until you cleaned up all application pods.

**Comment by Random-Liu** [comment]
@hmtai Can we close this issue? :)

**Comment by hmtai** [comment]
@Random-Liu OK.

**Comment by Random-Liu** [comment]
Close this issue based on https://github.com/containerd/cri/issues/732#issuecomment-383431820
