### ISSUE TITLE
Wrong version of golang

### ISSUE THREAD

**Issue by mikebrow** [containerd/cri#736]
is now possible..

Since containerd is now tracking updates to golang 1.10.x, we should also track for updates in CRI 

See: https://github.com/containerd/containerd/commit/37765fbde5b297b81bba2d1306f9abc84e8f775d

**Comment by Random-Liu** [comment]
Do it. :)

**Comment by Random-Liu** [comment]
Fixed in https://github.com/containerd/cri/pull/735. Close
