### ISSUE TITLE
portforward does not work when pod is using host network

### ISSUE THREAD

**Issue by qiujian16** [containerd/cri#738]
In our environment, we start tiller server with host network. We then connect to tiller with portforward using ```helm list```. And an error returns 
```
E0417 05:02:29.988555   22051 portforward.go:331] an error occurred forwarding 34086 -> 44134: error forwarding port 44134 to pod 6b79d2ed658ad32c0719b807e83f3fce882fc7271a28047ca3e21a6cc65b6e30, uid : network namespace for sandbox "6b79d2ed658ad32c0719b807e83f3fce882fc7271a28047ca3e21a6cc65b6e30" is closed
```

I think the check here https://github.com/containerd/cri/blob/master/pkg/server/sandbox_portforward.go#L57 fails. If a pod uses host network, I guess the network namespace will not be created?

**Comment by Random-Liu** [comment]
@qiujian16 Good catch!
