### ISSUE TITLE
Version mismatch? tarball vs release

### ISSUE THREAD

**Issue by ToroNZ** [containerd/cri#744]
Am I missing something here? Just realized that the tarball version doesn't align with the release version anymore.

![image](https://user-images.githubusercontent.com/8522935/38955765-b058fa34-43a9-11e8-8489-4e6169748b35.png)

Cheers

**Comment by Random-Liu** [comment]
@ToroNZ The release tarball is for containerd release, and containerd release version is `1.1.0-rc.2`.

We should probably publish the release tarball somewhere else. Putting it here just want people to see it.

**Comment by dmcgowan** [comment]
@Random-Liu we can publish the tarball there, but I agree we need to mention it in the release notes.

As for versioning, I wonder if in the future we want to sync up the version of containerd and the cri plugin after 1.0. We can see how confusing this is going forward, we may not want to have to release the plugin everytime we release containerd, but we will need to release containerd for every plugin update. @ToroNZ  do you have any recommendations for what would make this more clear?

**Comment by Random-Liu** [comment]
@dmcgowan User shouldn't care about `cri` version in the future, it is just something we use to track and manage progress in the `cri` project.

We should move all the user guides and the release tarball to a containerd place.
For document, we can move them to the containerd website, or docs repo?
For the release tarball, we can also move them to the containerd website, or publish as part of containerd release.

**Comment by Random-Liu** [comment]
We decided to publish the release tarball in containerd release note to avoid confusion. It is now part of containerd release now.

I think this issue should've been addressed.

Feel free to reopen if you think this is still confusing, and can be improved. :)
