### ISSUE TITLE
Disable restart manager in GCE deployment

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#772]
https://github.com/containerd/containerd/pull/2318 is useful for other use cases, e.g. using containerd to supervise system daemons.

But k8s deployment on GCE doesn't use it. We should disable it to avoid surprise, although unlikely.

**Comment by crosbymichael** [comment]
Can users reneable it?

**Comment by Random-Liu** [comment]
Yeah, it is just a config file change. We just disable the plugin by default in cloud-init.
