### ISSUE TITLE
Which ip address are we using when there are both IPv4 and IPv6?

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#783]
From the code, it is not very obvious to me:
* https://github.com/containerd/go-cni/blob/master/result.go#L82
* https://github.com/containerd/cri/blob/master/pkg/server/sandbox_run.go#L527

@abhi

**Comment by jingax10** [comment]
@abhi any update? Thanks!

**Comment by abhi** [comment]
The result from the cni plugin will have list of IPs for every interface. If there is 1 IP then it could be either ipv6 or ipv4 depending on what is assigned to each interface. So techincally if only IPv6 address is assigned, this what will be picked by cri-containerd.

**Comment by jingax10** [comment]
Thanks @abhi! In case CNI plugin return one IPv4 and IPv6 address for an interface, what is the rule to pick up the address for the pod? Is IPv4 be preferred? Thanks!

**Comment by abhi** [comment]
@jingax10 at this point it will be the first IP from the cni result. So essentially the ordering is defined by the cni plugin. Whatever it stamps as the first IP in the slice. 
Is there a preference we need to consider here ?

**Comment by jingax10** [comment]
@abhi, thanks for clarification! Could we get the same behavior as dockershim https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_sandbox.go#L336 does today? Thanks!

**Comment by abhi** [comment]
Do you happen to know about reason for that convention ? 
Mostly because there is a difference in the approach we took in cri using the go-cni library. 
We used the result from the cni plugin as the source of truth as opposed to checking the ip of the  interface inside the sandbox container.
