### ISSUE TITLE
Create deb/rpm packages?

### ISSUE THREAD

**Issue by luxas** [containerd/cri#827]
What do you think about creating deb/rpm packages for containerd?
The problem is, where (to what repos) should they get pushed?
We _could_ of course create debs/rpms from your binary releases in k8s/release, but I don't know whether that's a good solution long-term.

cc @timothysc @chuckha @detiber @feiskyer @Random-Liu

**Comment by mikebrow** [comment]
Good idea. But it's a dup:
https://github.com/containerd/containerd/issues/1508

**Comment by luxas** [comment]
Thanks!

**Comment by mikebrow** [comment]
Cheers!
