### ISSUE TITLE
How to configure private registry credential in containerd.toml

### ISSUE THREAD

**Issue by dawidmalina** [containerd/cri#835]
Can you help me how to properly configure private registry credential inside containerd.toml?

**Comment by Random-Liu** [comment]
If you are using containerd with Kubernetes, can you use `ImagePullSecrets`? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by dawidmalina** [comment]
Ok but is this the only way. Can we configure this on host level?

**Comment by Random-Liu** [comment]
Currently, there is no host level config for this.

What is your use case for host level credential config? If you want a default, we'd prefer you do it at the Kubernetes level. See [how to configure all pods in a specific namespace to use a default `ImagePullSecrets`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account).

**Comment by dawidmalina** [comment]
It would be nice to have drop in replacement for existing setup based on docker-ce where i don't use `ImagePullSecrets` as all configuration is done by configuration management tools. So i would like to have unchanged manifests and be able to switch from docker-ce to containerd.

**Comment by Random-Liu** [comment]
@dawidmalina Hm, make sense. Let me look into this. We should be able to add a config for this.

**Comment by Random-Liu** [comment]
@dawidmalina Does this meet your requirement? https://github.com/containerd/cri/pull/838

**Comment by dawidmalina** [comment]
Yes. Thank you.
