### ISSUE TITLE
When contaienrd load images,images tags changed 

### ISSUE THREAD

**Issue by hmtai** [containerd/cri#837]
First,I save image by docker:
```
docker save ibmcom/pause:3.0 -o pause.tar
```
Then I load image:
```
ctr cri load pause.tar
Loaded image: docker.io/ibmcom/pause:3.0
```
We can see that the image tag changed.Actually the image ID is the same.What's the matter with it?Should I config something to obtain my origin tags.

**Comment by mikebrow** [comment]
What makes you think something is wrong?

**Comment by Random-Liu** [comment]
@hmtai I think `ibmcom/pause:3.0` == `docker.io/ibmcom/pause:3.0`.

`ibmcom/pause:3.0` is just partial name, `docker.io/ibmcom/pause:3.0` is the actual normalized name. In `cri`, we keep all image name normalized now.

Does that cause any problem?

**Comment by mikebrow** [comment]
Yeah the tag hasn't changed, that's 3.0, docker.io is the default registry hostname to and from which the pushing and pulling is occurring. Long format for image names: [registry_host_name[:port]/]user_name/image_name[:tag_name]

**Comment by hmtai** [comment]
@Random-Liu Yes,I fell that  is `cri`image normalization,because during my ansible installation  I use `ibmcom/pause:3.0`instead of `docker.io/ibmcom/pause:3.0`image.

**Comment by Random-Liu** [comment]
@hmtai What do you mean? You can use both, and both should work.

**Comment by hmtai** [comment]
@Random-Liu I mean I hard code in ansible to use `ibmcom/pause:3.0`when create pods with docker,now I want to replace docker with cri-containerd but the images now is  `docker.io/ibmcom/pause:3.0`.

**Comment by mikebrow** [comment]
@hmtai, docker.io/ibmcom/pause:3.0 is the same image as ibmcom/pause:3.0. The image is the contents of pause.tar the name is a reference to the contents. You could call it foo/foo:1.0 if you wanted to and it would still be pause.tar and you would get the name docker.io/foo/foo:1.0 back from the ctr cri load api. docker.io does not mean you are using docker.. it's just a naming reference prefix. It just means docker.io is the default registry. I'm not sure why it's being added as a prefix in this case. But it shouldn't matter for what you are doing.

**Comment by hmtai** [comment]
@mikebrow I got it,thanks a lot:)

**Comment by Random-Liu** [comment]
@hmtai Can we close this one?

**Comment by hmtai** [comment]
Yes,close it.
