### ISSUE TITLE
Private registry without SSL not work

### ISSUE THREAD

**Issue by ProFfeSsoRr** [containerd/cri#853]
Trying to run private containers from private repo, containerd version v1.1.2.m 209a7fc3e4a32ef71a8c7b50c68fc8398415badf.m
Add this to my /etc/containerd/config.toml :
`[plugins.cri.registry.mirrors]
  [plugins.cri.registry.mirrors."my.registry.local"]
    endpoint = ["http://my.registry.local"]
`

Restart containerd, trying to pull image and see:
`pulling image failed: rpc error: code = Unknown desc = failed to resolve image "my.registry.local/group/package:latest": my.registry.local/group/package:latest not found`

Self-signed cert doesn't work too (with error "x509: certificate signed by unknown authority"). No way to use private registry now?

UPD. Problem in http headers. containerd use HEAD method, when I setup proxy and convert HEAD > GET everything start to work.

**Comment by Random-Liu** [comment]
@ProFfeSsoRr What private registry are you using?

Based on the docker registry v2 api, the registry should handle `HEAD /v2/`. See https://docs.docker.com/registry/spec/api/#pulling-an-image

/cc @dmcgowan

**Comment by ProFfeSsoRr** [comment]
Nexus OSS. If using only HEAD header is ok, I will close this ticket, sorry.
