### ISSUE TITLE
Document how to configure docker to share containerd with kubelet.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#861]
We should document how to configure docker with `docker --containerd` to share containerd with kubelet.

**Comment by resouer** [comment]
One note is how to handle version conflict?

i.e. the installed version of docker containerd conflicts with expectation of containerd/cri?

Or we will let users to handle the versions?

**Comment by Random-Liu** [comment]
Since Docker 18.09, containerd is a separate systemd service now.

No need to document how to separate containerd and docker any more.
