### ISSUE TITLE
validation test failure related to SELinux

### ISSUE THREAD

**Issue by vitt-bagal** [containerd/cri#871]
Built cri from source. Able to run unit test, integration test. while running validation tests using command `make test-cri`, one test related `SELinux` module is failing on RHEL 7.3:
`[k8s.io] SELinux runtime should support selinux [It] should error on create with wrong options`.          This test failures is observed only with `Enforcing` SELinux mode & with `Permissive` mode, All tests of SELinux module are getting skipped

## Expected Behavior
test should pass 

## Current Behavior
[BeforeEach] [k8s.io] SELinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:50
[BeforeEach] [k8s.io] SELinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:38
[BeforeEach] runtime should support selinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:47
[It] should error on create with wrong options
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:77
STEP: create a container with selinux
STEP: Get image status for image: busybox:1.28
STEP: Create container.
[AfterEach] runtime should support selinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:51
STEP: stop PodSandbox
STEP: delete PodSandbox
[AfterEach] [k8s.io] SELinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:51

тв Failure [0.803 seconds]
[k8s.io] SELinux
/tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
  runtime should support selinux
  /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:43
    should error on create with wrong options [It]
    /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:77

    Expected an error to have occurred.  Got:
        <nil>: nil

    /tmp/cri-install-crictl.STRb/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/selinux_linux.go:106

## Steps to Reproduce 

git clone https://github.com/containerd/cri $GOPATH/src/github.com/containerd/cri
cd $GOPATH/src/github.com/containerd/cri
git checkout v1.0.4
make install.deps
make
sudo make install
make test
make test-integration
make test-cri     

## Your Environment

* $ go version
go version go1.10.1 linux/amd64

* Operating System and version:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"

* $ getenforce
Enforcing

Can anyone please help in this?

**Comment by Random-Liu** [comment]
@miaoyq Can you take a look at this?

**Comment by mikebrow** [comment]
Just checking ... @vitt-bagal do you have libseccomp installed?

**Comment by mikebrow** [comment]
default config for containerd is enable_selinux = false... though if it's skipping the tests that going to be how critest validate is checking for selinux support.

**Comment by mikebrow** [comment]
Looks like this code for testing if selinux is enabled might be problematic. Maybe we should be using 
getenforce....

**Comment by mikebrow** [comment]
@miaoyq I'd start with updating to the latest selinux util.. https://github.com/kubernetes-incubator/cri-tools/blob/master/vendor.conf#L17 Looks like we're behind.

**Comment by miaoyq** [comment]
@mikebrow  Has this test passed after updating the selinux util?

**Comment by mikebrow** [comment]
No, I don't have a reproduction of the failure. I was curious and doing a quick investigation before Lantau asked you to look into it. There have been a lot of changes to the code in question (selinux.GetEnabled()) and the binaries that use it are way behind the current master. See cri-tools/critest validate, containerd/cri, and runc. Just an observation.

**Comment by miaoyq** [comment]
Seems not yet, we run CI test on ubuntu or similar systems that do not have selinux.

**Comment by miaoyq** [comment]
@mikebrow  Seems not yet, we run CI test on ubuntu or similar systems that do not have selinux.

**Comment by vitt-bagal** [comment]
@mikebrow I have tried to run test with changing **vendor.conf** file to use [b6fa367ed7f534f9ba25391cc2d467085dbb445a](https://github.com/opencontainers/selinux/commit/b6fa367ed7f534f9ba25391cc2d467085dbb445a) latest commit from master of opencontainers/selinux on **Rhel 7.3** as one work around, But still test failure is observed. currently this issue is observed on **RHEL** only

**Comment by miaoyq** [comment]
@vitt-bagal I will fix this failure. It‘s because the `level` of selinux options has not been verified.

**Comment by Random-Liu** [comment]
@miaoyq Thanks for fixing this!
