### ISSUE TITLE
TestVolumeOwnership test failure on Redhat Linux 7

### ISSUE THREAD

**Issue by vitt-bagal** [containerd/cri#882]
Built cri(v1.0.5 & v1.11.1)from source. But while running integration test on RHEL 7.3, TestVolumeOwnership test failure is observed.

## Expected Behavior
Test should pass

## Current Behavior
make test-integration FOCUS=TestVolumeOwnership
=== RUN   TestVolumeOwnership
--- FAIL: TestVolumeOwnership (3.59s)
       volume_copy_up_test.go:98: Create a sandbox
       volume_copy_up_test.go:107: Pull test image
       volume_copy_up_test.go:111: Create a container with volume-ownership test image
       volume_copy_up_test.go:120: Start the container
       volume_copy_up_test.go:125: Check ownership of test directory inside container
       volume_copy_up_test.go:133: Check ownership of test directory on the host
       Error Trace:    volume_copy_up_test.go:137
       Error:          Not equal: "nobody:nogroup\n" (expected)
                               != "nfsnobody:nfsnobody\n" (actual)

FAIL

## Steps to Reproduce (for bugs)

1. git clone https://github.com/containerd/cri $GOPATH/src/github.com/containerd/cri
2. cd $GOPATH/src/github.com/containerd/cri
3. git checkout v1.0.5 or git checkout v1.11.1
4. make install.deps
5. make & sudo make install
6. make test-integration

## Your Environment

* $ go version
   go version go1.10.1 linux/amd64
* Operating System and version
  NAME="Red Hat Enterprise Linux Server"
  VERSION="7.3 (Maipo)"

Can anyone please help in this?

**Comment by Random-Liu** [comment]
The test creates a container from a docker image which contains a `nobody:nogroup` volume https://github.com/containerd/cri/blob/master/integration/images/volume-ownership/Dockerfile#L17.

Underlying, containerd copies the volume from the image onto host, and mount back into the container. The ownership `nobody:nogroup` should also be copied during this process: https://github.com/containerd/cri/blob/master/pkg/containerd/opts/container.go#L117

However, based on the test result, it seems that the volume ownership is correct inside container, but on the host it becomes `nfsnobody:nfsnobody`. 

This is either a redhat specific behavior, or a bug inside https://github.com/containerd/cri/blob/master/vendor/github.com/containerd/continuity/fs/copy.go#L21.

Where does the `nfsnobody` come from?

**Comment by Random-Liu** [comment]
> Though nobody user & nogroup are present on host but test is picking nfsnobody as a user & group only.

@vitt-bagal Can you create a container with the test image with `crictl` or `kubectl`, and checks the ownership of the host path of the volume? Using this command: https://github.com/containerd/cri/blob/master/integration/volume_copy_up_test.go#L134

**Comment by vitt-bagal** [comment]
>Can you create a container with the test image with crictl or kubectl, and checks the ownership of the host path of the volume? 

@Random-Liu I have tried it container . In container also it shows **ownership** of volume as `**nfsnobody**`. This behavior is observed on **RHEL** only. So can you update test accordingly for redhat ?

**Comment by kzys** [comment]
FYI, RHEL 8 apparently doesn't have `nfsnobody` anymore.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/shells-and-command-line-tools_considerations-in-adopting-rhel-8

>  Red Hat Enterprise Linux (RHEL) 7 used the nobody user and group pair with the ID of 99 and the nfsnobody user and group pair with the ID of 65534, which is also the default kernel overflow ID.
> In RHEL 8, both of these pair have been merged into the nobody user and group pair, which uses the ID of 65534. The nfsnobody pair is not created in RHEL 8.
> This change reduces the confusion about files that are owned by nobody but are not related to NFS.
