### ISSUE TITLE
Multiple CNI configuration files cause pod network setup failed

### ISSUE THREAD

**Issue by zerda** [containerd/cri#889]
Apologize first if this is the wrong repo to report.

I have create an kubernetes cluster with 1 master, 2 workers. A worker is running with docker, another with containerd.

Kubernetes: v1.11.2
Docker: docker.io 17.03.2-0ubuntu2~16.04.1
Containerd: v1.2.0-beta.1
Weave Net: v2.4.0

In `/etc/cni/net.d/` folder, there are two files `00-weave.conflist` and `10-weave.conf`.

`00-weave.conflist` file is for host port mapping.
```json
{
    "cniVersion": "0.3.0",
    "name": "weave",
    "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {
                "portMappings": true
            },
            "snat": true
        }
    ]
}
```

`10-weave.conf` is automatically created by weave-net pod when file is missing.
```json
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true
}
``` 

At following specific situation in containerd, weave-net failed to setup network for pod, but works in docker.
- All two files exist in `/etc/cni/net.d/`
- Reboot the worker node

The error is `failed to setup network for sandbox "8503e1c461e68e9f1effe68fb336040e852ead28e4837bf4db3d4795cc36ceb2": could not create veth pair vethwepl8503e1c-vethwepg8503e1c: file exists`.

If only one configuration file (either 00-weave.conflist with an empty 10-weave.conf file, or 10-weave.conf only) exists, everything is working fine with containerd after the reboot.

From [Network Plugins in Kubernetes Documentation](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)
> If there are multiple CNI configuration files in the directory, the first one in lexicographic order of file name is used.

I'm wondering if `10-weave.conf` should be ignored or not.

Thank you.

**Comment by Random-Liu** [comment]
We do sort the config files https://github.com/containerd/go-cni/blob/master/opts.go#L163

/cc @abhi

**Comment by Random-Liu** [comment]
I think the problem is that in this case, we attach network for both configurations:
https://github.com/containerd/go-cni/blob/master/cni.go#L107

While, dockershim only returns and attaches one default network. https://github.com/kubernetes/kubernetes/blob/dbe3b1a3b37c70813d0b36d50143eb23cb37cb91/pkg/kubelet/dockershim/network/cni/cni.go#L119

@abhi
