### ISSUE TITLE
Node goes Not Ready because of cri-containerd and containerd issues 

### ISSUE THREAD

**Issue by mootezbessifi** [containerd/cri#899]
Hi All,

i am running with a very very strange issue since 2 weeks ago.
let me describe in details what happened:

1. k8s node status Ready.
2. After few time (maybe 1 or 2 days maximum) node Status will be Not Ready with the following description:
[kubectl describe node.txt](https://github.com/containerd/cri/files/2363245/kubectl.describe.node.txt)

3. when i tried to open kubelet log i found the below:

[kubelet.log](https://github.com/containerd/cri/files/2363251/kubelet.log)

4. same thing i got logs for cri-containerd and containerd services

[cri-containerd.log](https://github.com/containerd/cri/files/2363254/cri-containerd.log)

[containerd.log](https://github.com/containerd/cri/files/2363256/containerd.log)

At this stage when i try to list sandboxes, using `sudo crictl sandboxes` and hangs for long time without giving any result.
Some kubernetes issues was commenting the `PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s` issue is that this is due to huge number of images in node. i was not running with such case but i cleaned up all images but unfortunately the issue appear after few time.

I am getting also the bellow issue from containerd which i do not know what it means:
`INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1`
`INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1`
`WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd`
`INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1`
`INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1`
`WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"`

my kubernetes cluster is running with the bellow info:

OS master and nodes: ubuntu 16.04
k8s version: 1.9.6
cri-containerd: 1.0.0-beta.1
containerd: `containerd github.com/containerd/containerd v1.0.0-6-g6c7abf7 6c7abf7c76c1973d4fb4b0bad51691de84869a51`

The only fix which i have now is to restart the node and it becomes directly Ready.
Also, yesterday i tried to delete all pods and sandboxes in the failed node using the `ctr` command,  the containers were deleted directly but the sandboxes where not fully deleted. the `ctr` command hangs so i stopped the containerd.service and tried to remove them manually from `/var/lib/cri-containerd/sandboxes` directory. it returms me `directory or device busy`. 
After advanced investigation i found out even the containerd.service stopped but there are processes running in the background related to it still running so i force delete them and restarted both cri-containerd and containerd services. So the node become Ready Again.

Please i need to fix this ASAP because it is a show stopper issue.
Any contribution to resolve this issue will be very appreciated.

**Comment by mikebrow** [comment]
I suspect you are running into an issue that has been fixed since the beta release. There have been a small number of fixes that addressed issues around deleting sandboxes. We merged cri-containerd into containerd v1.1+ before we went GA on kubernetes 1.10+. Unfortunately there were breaking changes to the CRI alpha2 interface used in kubernetes 1.10 so when we moved up to 1.10 we ended up only supporting kubernetes 1.10 and above with containerd 1.1 and above.  

Is it possible for you to test on 1.10 or 1.11 kube with a GA version of containerd w/cri support to see if we've already fixed your issue? 

Note: there was also a fix to sandbox deletion that went into master a couple weeks ago and should show up as a cherry pick on a service update to the GA releases soon:
https://github.com/containerd/cri/commit/140a6f489b335f5ce5a1e32eb61aa655f9a6fafe

@Random-Liu wdyt?

**Comment by mootezbessifi** [comment]
Hi @mikebrow 
thank you a lot for your detailed answer, i have another k8s cluster v1.10.6 and using containerd version 1.1.0. do this fix is reflected to that version because in [https://github.com/containerd/cri/commit/140a6f489b335f5ce5a1e32eb61aa655f9a6fafe](140a6f4) in found out that it is merged to v 1.11.0, or i should upgrade.

**Comment by mikebrow** [comment]
After we merged the version you get is the containerd version. Sorry about the confusion.

While there were a number of fixes to deleting containers / sandboxes in the latest releases of containerd https://github.com/containerd/containerd/releases/tag/v1.2.0-beta.2 and https://github.com/containerd/containerd/releases/tag/v1.1.3, neither has the 
https://github.com/containerd/cri/commit/140a6f489b335f5ce5a1e32eb61aa655f9a6fafe fix just yet.

**Comment by Random-Liu** [comment]
@mootezbessifi `cri-containerd` is deprecated half a year ago. https://github.com/containerd/cri/issues/642

Many fixes are not cherry-picked there. Please use containerd 1.1+ instead. :)
