### ISSUE TITLE
How to configure CRI to support devicemapper

### ISSUE THREAD

**Issue by keyingliu** [containerd/cri#900]
I'm evaluating cri-containerd in our k8s cluster, I would like to use devicemapper as storage backend instead of overlayfs, but after going through all the documents in this repo, I didn't find the guide how to configure devicemapper. Can anyone please guide me to the correct link? Thanks!

**Comment by estesp** [comment]
Devicemapper backend has not been implemented as a snapshotter in containerd, so there is no way to use devicemapper today. Someone would have to commit to create and support a devicemapper plugin, as the core maintainers of containerd made a design decision not to implement/support devicemapper natively. I believe Red Hat has done significant work in RHEL to properly support overlay in recent RHEL releases such that devicemapper should not be required for a modern RHEL installation.

**Comment by Random-Liu** [comment]
@keyingliu Hi! Thanks for filing the issue. I'd like to know why you need devicemapper, because of the OS distro?

**Comment by keyingliu** [comment]
@Random-Liu we are running thousands of nodes in several k8s clusters in our data center, currently the direct-lvm is the storage backend for our docker runtime, as we still found there are some overlayfs issues that cannot satisfy our requirements.

**Comment by keyingliu** [comment]
For example, yum install might fail in container with overlayfs, and a good summary of issue list for all storage backend: https://github.com/AkihiroSuda/issues-docker

**Comment by AkihiroSuda** [comment]
Do native or zfs work for you?

**Comment by AkihiroSuda** [comment]
Also note that yum-plugin-ovl is available by default on most Docker Hub images as the workaround for the issue

**Comment by AkihiroSuda** [comment]
Firecracker-containerd provides devicemapper plugin for containerd: https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter/devmapper

**Comment by clarklee92** [comment]
Yep, I noticed that  a week ago, as I known, firecracker-containerd is a baby project. @AkihiroSuda Have you ever tried it in production env?

**Comment by AkihiroSuda** [comment]
no

**Comment by 0902horn** [comment]
The device mapper snapshotter has been merged into containerd (https://github.com/containerd/containerd/issues/2988#issuecomment-478712714). 
I think we may have some updates on this issue.

**Comment by keyingliu** [comment]
Thanks. After taking much effort, we converted the storage backend from devmap to overlayfs although we found some issues:
- dead lock that caused too many d state process and made nodes ran into issues: https://github.com/torvalds/linux/commit/bc56ad8c74b8588685c2875de0df8ab6974828ef
- no quota for overlayfs, a container can easily make disk full.
