### ISSUE TITLE
Consolidate `ctr cri load` and `ctr import`

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#909]
After https://github.com/containerd/cri/pull/865 is in, `cri` can see images pulled/loaded by `ctr`.

We should be able to ues `ctr import` instead of `ctr cri load` once https://github.com/containerd/containerd/pull/2633 is in.

And then we should start deprecating `ctr cri load`.

**Comment by NicolasT** [comment]
Is this blocked by something? All referenced PRs seem to be in, however (using `containerd` 1.2.1 and 1.2.3) I'm unable to get `ctr images import` and `crictl images` to align, or `ctr cri load` and `ctr images ls` to align either. Furthermore, an image loaded using `ctr cri load` which shows up in `crictl images` doesn't result in any objects in `ctr content ls`.

This despite the `containerd` 1.2.0 release notes saying

> cri plugin can see images pulled/imported into containerd by ctr images pull and ctr images import

which I haven't been able to reproduce in my testing.

**Comment by Random-Liu** [comment]
@NicolasT You need to specify `--namespace=k8s.io` when using `ctr`.

Containerd supports namespaces, and the cri plugin is using the `k8s.io` namespace.

**Comment by Random-Liu** [comment]
We should evaluate `ctr images import` to see whether it meets all our requirement.
If yes, we should start deprecating `ctr cri load` since 1.3

**Comment by Random-Liu** [comment]
We should start deprecating `ctr cri load` in 1.3, probably:
1) Print deprecation notice first;
2) Remove in containerd 1.4

@dmcgowan WDYT?

**Comment by Random-Liu** [comment]
The `ctr cri load` command is removed. https://github.com/containerd/cri/pull/1170

Only thing left for this issue is the 1.3 release note update.

**Comment by jterry75** [comment]
Thanks for the work @Random-Liu !

**Comment by Random-Liu** [comment]
The update for this will be included in https://github.com/containerd/containerd/pull/3492.
