### ISSUE TITLE
Cleanup after shim v1 is deprecated.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#946]
In https://github.com/containerd/cri/pull/943, we added better support of containerd shim v2.

Now each runtime can have its own option type. Config options and code dedicated to the runtime type `io.containerd.runtime.v1.linux` will start being deprecated, including `no_pivot`, `systemd_cgroup`, `runtime_engine` and `runtime_root`.

We should:
1) document the deprecation and new runtime config in the release note (containerd 1.2)
2) get rid of those and cleanup the code and config after shim v1 is deprecated (future).

I'll mark the issue as 1.2 for now, until we added necessary information into the release note.

**Comment by Random-Liu** [comment]
We've done 1). I'll move this out of v1.2.

**Comment by jterry75** [comment]
@Random-Liu - Should this be in 1.3?

**Comment by mikebrow** [comment]
@Random-Liu @dmcgowan did a quick skim.. don't see that we've deprecated the v1 shim publically yet.. is there a plan for that or will it just fade away :-)
