### ISSUE TITLE
Do not log AuthConfig as it leaks passwords

### ISSUE THREAD

**Issue by dadux** [containerd/cri#960]
(Initially reported through security@containerd.io)

When using Auth for image registries, the password gets leaked in the logs : 
```
Oct 25 05:21:04 ip-10-151-119-59.ec2.internal containerd[32940]: time="2018-10-25T05:21:04.477315296Z" level=info msg="PullImage "docker.atl-paas.net/kitt/my_image:v0.6.0" with auth config &AuthConfig{Username:kitt-bbcidev-bot,Password:__REDACTED__:,ServerAddress:,IdentityToken:,RegistryToken:,}
```

Should the AuthConfig be logged at all ?

**Comment by Random-Liu** [comment]
@mikebrow Can you cherrypick your fix into supported branches?

**Comment by Random-Liu** [comment]
The change is cherrypicked to both release/1.1 and release/1.2.

Time to close now.
