### ISSUE TITLE
#bug#k8s Untrusted pod' network namespace was still exist after pod deleted

### ISSUE THREAD

**Issue by clarklee92** [containerd/cri#968]
Many thanks to the containerd CRI contributors! Using kata and runc in a k8s cluster becomes possible helps my team a lot.
There is a bug I found recently. When using pod with runc  everything is ok, but after kata Pod deleted the cni network namespace wasn't deleted with Pod.
The result is that once kata pod created the network namespace number added.
I check netns with:  ip netns ls
your Sincerely
clark lee

**Comment by Random-Liu** [comment]
Is this related to https://github.com/containerd/containerd/issues/2546? @linxiulei

**Comment by clarklee92** [comment]
Thanks a lot.

**Comment by clarklee92** [comment]
> Is this related to [containerd/containerd#2546](https://github.com/containerd/containerd/issues/2546)?

Hi, LanTao. Today I read related code in cri plugin and I thought my issue may be new.
I use the latest version containerd 1.2.0,  the pod and it's network already deleted before netns. 
There may be some useful information I can offer：
The log in `journalctl -u cri.service` printed reduplicative and endless error:
/*level=error msg="StopPodSandbox for "2d17c2e7703511f167800efda53969bf2df8669e9e0f861671d2f19515e5b55e" failed" error="failed to destroy network for sandbox "2d17c2e7703511f167800efda53969bf2df8669e9e0f861671d2f19515e5b55e": failed to get IP addresses for "eth0": <nil>"*/
Which is throwed from function <c.netPlugin.Remove>
Kata Pod has a special netns cause It's IP has to be mapped into Pod. The netns like this:
>eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet6 fe80::c468:e8ff:fe88:dbe6  prefixlen 64  scopeid 0x20<link>
        ether 02:00:ca:fe:00:00  txqueuelen 0  (Ethernet)
        RX packets 10  bytes 732 (732.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25  bytes 2022 (1.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap0_kata: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet6 fe80::858:acff:fe1f:8  prefixlen 64  scopeid 0x20<link>
        ether 0a:58:ac:1f:00:08  txqueuelen 1500  (Ethernet)
        RX packets 2  bytes 84 (84.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17  bytes 1374 (1.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

"eth0" has no IP address is expected. So the function need  to fit Kata without get netns ip.

Thanks
Sincerely yours
clark lee

**Comment by clarklee92** [comment]
> > Is this related to [containerd/containerd#2546](https://github.com/containerd/containerd/issues/2546)?
> 
> Hi, LanTao @Random-Liu . Today I read related code in cri plugin and I thought my issue may be new.
> I use the latest version containerd 1.2.0, the pod and it's network already deleted before netns.
> There may be some useful information I can offer：
> The log in `journalctl -u crio.service` printed reduplicative and endless error:
> 
> > level=error msg="StopPodSandbox for "2d17c2e7703511f167800efda53969bf2df8669e9e0f861671d2f19515e5b55e" failed" error="failed to destroy network for sandbox "2d17c2e7703511f167800efda53969bf2df8669e9e0f861671d2f19515e5b55e": failed to get IP addresses for "eth0": <nil>"
> 
> Which is throwed from function <c.netPlugin.Remove>
> Kata Pod has a special netns cause It's IP has to be mapped into Pod. The netns is like this:
> 
> > eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
> > inet6 fe80::c468:e8ff:fe88:dbe6  prefixlen 64  scopeid 0x20
> > ether 02:00:ca:fe:00:00  txqueuelen 0  (Ethernet)
> > RX packets 10  bytes 732 (732.0 B)
> > RX errors 0  dropped 0  overruns 0  frame 0
> > TX packets 25  bytes 2022 (1.9 KiB)
> > TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> > lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
> > inet 127.0.0.1  netmask 255.0.0.0
> > inet6 ::1  prefixlen 128  scopeid 0x10
> > loop  txqueuelen 1000  (Local Loopback)
> > RX packets 0  bytes 0 (0.0 B)
> > RX errors 0  dropped 0  overruns 0  frame 0
> > TX packets 0  bytes 0 (0.0 B)
> > TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> > tap0_kata: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
> > inet6 fe80::858:acff:fe1f:8  prefixlen 64  scopeid 0x20
> > ether 0a:58:ac:1f:00:08  txqueuelen 1500  (Ethernet)
> > RX packets 2  bytes 84 (84.0 B)
> > RX errors 0  dropped 0  overruns 0  frame 0
> > TX packets 17  bytes 1374 (1.3 KiB)
> > TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> "eth0" has no IP address is expected, the function may need to fit Kata without getting netns ip.
> 
> Thanks
> Sincerely yours
> clark lee

I come to end this issue, It's not a bug at all! The only reason cause this issue is that CNI version.
Just update the CNI plugins to latest!

**Comment by Random-Liu** [comment]
@clarklee92 Thanks for updating! :) I'll close this issue. Feel free to reopen if needed.
