### ISSUE TITLE
Doubtful about using kubenet in containerd(with conf_template specified)

### ISSUE THREAD

**Issue by clarklee92** [containerd/cri#978]
Dear developers：
  In #724 I tried to use containerd in our existing "kubenet" cluster, I am sure my usages are right and the cni configure is generated as respected. Here my cni.template.conf:
>{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cbr0",
      "mtu": 1400,
      "addIf": "eth0",
      "isGateway": true,
      "ipMasq": false,
      "hairpinMode": false,
      "ipam": {
        "type": "host-local",
        "subnet": "{{.PodCIDR}}",
        "routes": [
          {"dst": "0.0.0.0/0"}
        ]
      }
    }
  ]
}

When I use docker-shim and then change CRI to containerd, the cluster network was ok.
But when I deployed a new cluster with containerd straightforward(with no docker and --network-plugin=kubenet), the dns pod couldn't get the status of liveness probe(essentially api-server couldn't be connected). I tried lots of ways in google and issue still. 
Looking for help here if there is some suggesting.

**Comment by Random-Liu** [comment]
This sounds like a sysctl issue to me.

Have you set `net.bridge.bridge-nf-call-iptables=1` and `net.ipv4.ip_forward=1` on your nodes?

**Comment by clarklee92** [comment]
> This sounds like a sysctl issue to me.
> 
> Have you set `net.bridge.bridge-nf-call-iptables=1` and `net.ipv4.ip_forward=1` on your nodes?

Yes, I already did that. Our cluster works on line with docker for a long time, and I only changed the deployment code using containerd to replace docker. As a result, the cluster network is wrong.

**Comment by clarklee92** [comment]
I tried Flannel on this new cluster and it's ok, but we have to use kubenet  as many other reasons.
I want to make it clear how to use kubenet with containerd felicitously. The CNI conf I got was from kubelet log when using docker. I switched it to containerd and used cni.template to get podCIDR and it worked fine.
Did the docker with k8s kubenet has some necessary initialization？
>Normal   Started    27m (x2 over 29m)   kubelet, 192.168.0.30  Started container
  Normal   Created    27m (x2 over 29m)   kubelet, 192.168.0.30  Created container
  Warning  Unhealthy  27m (x3 over 27m)   kubelet, 192.168.0.30  Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  BackOff    18m (x28 over 26m)  kubelet, 192.168.0.30  Back-off restarting failed container
  Warning  BackOff    8m (x31 over 16m)   kubelet, 192.168.0.30  Back-off restarting failed container
  Warning  Unhealthy  3m (x54 over 28m)   kubelet, 192.168.0.30  Readiness probe failed: Get http://172.18.0.7:8081/readiness: dial tcp 172.18.0.7:8081: connect: connection refused

The pod can't get api-server and reboot always. Please take a look , thank you very much!

**Comment by clarklee92** [comment]
Please end this issue. I final figure out that when using kubenet with containerd, you need set:
>      "ipMasq": true,
         "promiscMode": true,

That's different with docker, I guess docker's start up parameter “--iptables=false" may did the same thing. Hope to help others with the same confusion.

**Comment by Random-Liu** [comment]
@clarklee92 Thanks! That's the point of conf_template. :)

You can configure it in anyway you need. :P 

I'll close this issue for now, and thanks for filing the issue and posting the solution here!
