### ISSUE TITLE
Periodically refresh CNI configuration

### ISSUE THREAD

**Issue by caseydavenport** [containerd/cri#981]
Hopefully this is the right place to raise this.

Recently had some users hitting this issue: https://github.com/projectcalico/calico/issues/2200

It turned out to be that when using containerd with Kubernetes, CNI config file changes on disk are not picked up without a restart of containerd. 

When using docker, CNI config is periodically reloaded, and so changes are picked up for future containers. It would be great if the same was true when using containerd as the runtime.

**Comment by mikebrow** [comment]
What release are you on? We fixed this last June. When a pod is created we use the current cni config files for that pod.

**Comment by mikebrow** [comment]
See https://github.com/containerd/cri/pull/825 :-)

**Comment by caseydavenport** [comment]
@mikebrow thanks for the pointer, I think it is likely that an older version is in use then. I'll double check and report back here.

**Comment by caseydavenport** [comment]
Yep, looks like it was an older version. Sorry for the noise - thanks!
