### ISSUE TITLE
Container life cycle should not rely on the existence of other image references.

### ISSUE THREAD

**Issue by Random-Liu** [containerd/cri#990]
Containerd manages images based on references. Image names (tag, id etc.), container references are all valid independent references.

They are independent, means that you can remove all image references, and the container can still run happily because the snapshots are still referenced. This also means that **we can't assume image references (and the content) exist across the whole life cycle of a container using the image**.

However, we are doing so in some container operations:
* ContainerStop: https://github.com/containerd/cri/blob/master/pkg/server/container_stop.go#L80
* ContainerStatus: https://github.com/containerd/cri/blob/master/pkg/server/container_status.go#L44

This causes issue like https://github.com/containerd/containerd/issues/2858.

There are 2 options to fix this:
* **Option 1**: Add logic in the cri plugin to avoid deleting image references when container is still using an image.
  * Problem 1: This is racy. It is always possible that after you check and make sure that an image is not in use, a new container is created referencing the image. Need to add synchronization for this case.
  * Problem 2: Users can always delete image references by talking with containerd directly. We don't have any control to that.
* **Option 2**: Always assume that image reference may be gone after container creation, and never rely on it in the container lifecycle.

Given the problem of option 1, I prefer option 2.

For option 2:
1) [For `StopContainer`, only `StopSignal` is needed](https://github.com/containerd/cri/blob/master/pkg/server/container_stop.go#L80), we should add it into container metadata during container creation; 
2) [For `ContainerStatus`, the image `id` to `tag` conversion is best effort anyway,](https://github.com/containerd/cri/blob/master/pkg/server/container_status.go#L46) just don't return error.

Note that adding `StopSignal` into metadata is adding a new field into our metadata checkpoint. We should handle in place upgrade properly.

**Comment by mikebrow** [comment]
agree option 2

**Comment by Random-Liu** [comment]
At a second thought, I think we need both option 1 and 2.

We need option 1, because that is Docker's behavior, I think people expect that in `crictl`. And even for Kubernetes garbage collection, it is an important piece to avoid race condition:
1) Kubelet compares container and image list, and find an unused image;
2) New container created using the image;
3) Kubelet garbage collects the image.

Currently, for Docker, 3) will fail; but for containerd 3) will remove the image.

**Comment by mikebrow** [comment]
ok, thx for investigating! agree option 1 with tolerance for option 2.

**Comment by mikebrow** [comment]
suggest adding an issue to enable the garbage collect of the in use image.. (breaking the bad employed exhibited by docker)
